### ISSUE TITLE
大神图表的点击事件回调不出来哦，是怎么回事

### ISSUE THREAD

**Issue by pressureKai** [AAChartModel/AAChartCore-Kotlin#1]
我让我的Fragment实现了 AAChartView.AAChartViewCallBack这个接口
![image](https://user-images.githubusercontent.com/28721119/62516533-f4309180-b857-11e9-9d04-363aadb49373.png)
并设置callback，是可以检测到加载完成的回调，但是点击事件没有反应
![image](https://user-images.githubusercontent.com/28721119/62516646-36f26980-b858-11e9-91f2-22f2b6310137.png)
点进源码发现chartViewMoveOverEventMessage这个接口应该没有被回调过
![image](https://user-images.githubusercontent.com/28721119/62516730-6ef9ac80-b858-11e9-8d17-f4d0ae321333.png)
不知道是不是我理解的这样，您看一下

**Comment by AAChartModel** [comment]
周末有时间看看,应该不是大问题
