### ISSUE TITLE
请问，代码混淆时应该注意哪些文件？我增加代码混淆后图表只显示一个“Chart title”

### ISSUE THREAD

**Issue by RDSunhy** [AAChartModel/AAChartCore-Kotlin#10]
请问，代码混淆时应该注意哪些文件？我增加代码混淆后图表只显示一个“Chart title”

**Comment by RDSunhy** [comment]
我的混淆文件
`-flattenpackagehierarchy
-allowaccessmodification
-keepattributes Exceptions,InnerClasses,Signature,SourceFile,LineNumberTable,
-dontskipnonpubliclibraryclassmembers
-ignorewarnings
#kotlin
-keep class kotlin.** { *; }
-keep class kotlin.Metadata { *; }
-dontwarn kotlin.**
-keepclassmembers class **$WhenMappings {
    <fields>;
}
-keepclassmembers class kotlin.Metadata {
    public <methods>;
}
-assumenosideeffects class kotlin.jvm.internal.Intrinsics {
    static void checkParameterIsNotNull(java.lang.Object, java.lang.String);
}

-keepclasseswithmembernames class * {
    native <methods>;
}

-keepclassmembers class * extends android.app.Activity {
   public void *(android.view.View);
}
-keepclassmembers class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
-keep class **.R$* {*;}
-keepclassmembers enum * { *;}`

**Comment by AAChartModel** [comment]
想要查出此问题的原因,需要看你配置生成的 AAOptions 转化成 JSON 字符串的具体信息了. 很有可能是在你混淆代码的时候,破坏了AAChartCore 中的原有的类名的或原有的属性名称,导致的此问题.

**Comment by AAChartModel** [comment]
很有可能是在你混淆代码的时候,破坏了AAChartCore 中的原有的类名的或原有的属性名称,导致了最终生成的 Json 的键值对中的键名有问题,AAChartView.html 文件中的 JS 文件不能有效取值,因而产生了此问题.

**Comment by RDSunhy** [comment]
非常感谢，我在混淆时排除了AAChartConfiger和AAOptionsModel两个包下的文件就ok了。还有一个小问题，图表无数据时有没有什么配置？现在无数据时显示空白感觉体验不太好，demo中我没有找到相关的配置

**Comment by AAChartModel** [comment]
难道你要的是这种效果?

![image](https://user-images.githubusercontent.com/16357599/71863042-9837a500-3136-11ea-8e78-254f7035920d.png)

**Comment by RDSunhy** [comment]
是的 是这种效果，我又去翻了一下demo，还是没找到= =!。这个是在哪里设置的？

**Comment by AAChartModel** [comment]
目前还没加这个功能😅
