### ISSUE TITLE
AAXAxis tickPositions is missing

### ISSUE THREAD

**Issue by sabvente** [AAChartModel/AAChartCore-Kotlin#114]
AAXAxis tickPositions is missing.

iOS has it here:
* https://github.com/AAChartModel/AAChartKit-Swift/blob/master/AAInfographics/AAOptionsModel/AAXAxis.swift#L89

**Comment by AAChartModel** [comment]
It was fixed in this commit 

* https://github.com/AAChartModel/AAChartCore-Kotlin/commit/7e11cda46b0ad29c3a0ad1f275c07e81e7c0728e

Update AAChartCore-Kotlin to the latest content then you can find it.
