### ISSUE TITLE
下面这两种效果支持么

### ISSUE THREAD

**Issue by BaiMingxu** [AAChartModel/AAChartCore-Kotlin#117]
![WechatIMG131](https://user-images.githubusercontent.com/22886455/163435205-374a08ea-233c-4214-9b63-9845e5d02d90.jpeg)
![WechatIMG132](https://user-images.githubusercontent.com/22886455/163435222-f092fb84-bc29-4e5f-a824-6515a7e6dddb.jpeg)

**Comment by AAChartModel** [comment]
支持, 在 demo 中可以找到相关示例.
