### ISSUE TITLE
AAChartViewCallBack callback完全无法使用

### ISSUE THREAD

**Issue by GrizzlyRen** [AAChartModel/AAChartCore-Kotlin#119]
请教一下大佬，图表正常使用的时候，设置callback，chartViewDidFinishLoad可以正常回调，但是chartViewMoveOverEventMessage无法被回调，如何解决？

**Comment by GrizzlyRen** [comment]
补充一下，demo是正常可以回调的

**Comment by InnocentYang** [comment]
这个问题我遇到过，需要手动把触摸事件打开

`return new AAChartModel()
    ......
    .touchEventEnabled(true)
    ......                
`

**Comment by GrizzlyRen** [comment]
> 这个问题我遇到过，需要手动把触摸事件打开
> 
> `return new AAChartModel() ...... .touchEventEnabled(true) ...... `

非常感谢大佬的指导，现在可以使用了
