### ISSUE TITLE
您好，请问有没有交流群

### ISSUE THREAD

**Issue by liuhuan8986** [AAChartModel/AAChartCore-Kotlin#120]

**Comment by AAChartModel** [comment]
抱歉, 目前没有 AAChartCore 的交流群, 至于原因参考:

* https://github.com/AAChartModel/AAChartKit/issues/1066

**Comment by AAChartModel** [comment]
有 AAChartKit 版本的交流群, 参考:

* https://github.com/AAChartModel/AAChartKit/issues/502

不过由于精力有限, 不是我本人在维护.
