### ISSUE TITLE
为什么ios在一直更新，安卓就停止维护了呢？

### ISSUE THREAD

**Issue by GrizzlyRen** [AAChartModel/AAChartCore-Kotlin#128]

**Comment by AAChartModel** [comment]
没有停止维护啊, 你可以看到我最近一次提交还是在 6 天前呢, 我的目标至少会维护十年以上的, 现在还早呢 🐶

**Comment by AAChartModel** [comment]
查看此仓库活动统计图表: https://github.com/AAChartModel/AAChartCore-Kotlin/graphs/contributors
