### ISSUE TITLE
区域折线图线条层级关系

### ISSUE THREAD

**Issue by lhpkxywm** [AAChartModel/AAChartCore-Kotlin#131]
![image](https://user-images.githubusercontent.com/12290214/183636156-a68c4ccc-ebca-4d41-8d75-aca6cac889e8.png)
如图，我把红色的部分设在了最里头，这样填充图就不会盖住其它线条了，但是这样红色的线条又被其他折线覆盖了

我希望红色线条在最外侧，不被其它线条覆盖，同时它的填充色也不会覆盖其它线条。

**Comment by AAChartModel** [comment]
你的这个需求
* 本质上需要折线填充图的`折线`和`渐变填充色`不在同一个图层, 
* 然而 HIghcharts 的折线填充图的`折线`和`渐变填充色`只能在一个图层.

**Comment by AAChartModel** [comment]
查看
* https://api.highcharts.com/highcharts/series.area.zIndex
虽然支持通过设置 zIndex 来调整层级, 但是仍然不能改变 HIghcharts 的折线填充图的`折线`和`渐变填充色`**在一个图层**的根本问题.

**Comment by AAChartModel** [comment]
目前我能想到的, 只能是这种非常规的方式:

* 将单独的一个 `area` 类型的 `AASeriesElement` 拆成两个.
* 其中一个 `AASeriesElement` 用来显示红色`渐变填充色`, 并禁用选中交互效果.
* 另一个 `AASeriesElement`用来显示红色`折线`.


用代码来说明:

差不多是将

```swift
 [
        AASeriesElement()
            .type(.area)
            .color(AAColor.red)
            .lineWidth(5)
            .fillColor(AARgba(255, 0, 0, 0.3))
            .data([49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4])
        ,
    ]
```

拆分成

```swift
        let dataArr = [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]

 [
        AASeriesElement()
            .type(.area)
            .lineWidth(0)
            .fillColor(AARgba(255, 0, 0, 0.3))
            .allowPointSelect(false)//禁用选中效果
            .data(dataArr)
        ,
        AASeriesElement()
            .type(.line)
            .color(AAColor.red)
            .lineWidth(5)
            .data(dataArr)
        ,
    ]
```

差不多是这种效果.
