### ISSUE TITLE
title如何设置底部居中？

### ISSUE THREAD

**Issue by wealive** [AAChartModel/AAChartCore-Kotlin#134]
align(AAChartAlignType.Center)
verticalAlign(AAChartVerticalAlignType.Bottom)不起作用

**Comment by AAChartModel** [comment]
如下配置即可

```kotlin
    fun customTitleStyle(): AAOptions {
        val aaChartModel = AAChartModel()
            .legendEnabled(false)
            .categories(arrayOf(
                    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
                ))
            .series(arrayOf(
                    AASeriesElement()
                        .data(arrayOf(149.9, 171.5, 106.4, 129.2, 144.0, 176.0, 135.6, 188.5, 276.4, 214.1, 95.6, 54.4))
            ))
        val aaOptions = aaChartModel.aa_toAAOptions()
        aaOptions.chart?.marginBottom = 100
        aaOptions.title?.apply {
             text("This is the custom title")
            .align(AAChartAlignType.Center)
            .verticalAlign(AAChartVerticalAlignType.Bottom)
            .y(10)
        }
        return aaOptions
    }
```

**Comment by AAChartModel** [comment]
参考:
* https://api.highcharts.com/highcharts/title.verticalAlign

**Comment by AAChartModel** [comment]
注意这行代码

```kotlin
        aaOptions.chart?.marginBottom = 100
```

为底部腾出空间.

**Comment by wealive** [comment]
不行，title还是不能到饼图底部，设置没有用，需要的是底部居中 
val aaOptions = chartModel.aa_toAAOptions().apply {
            chart?.marginBottom=100
            title?.apply {
                style(AAStyle().fontSize(12).color("#333333"))
                text("第${position}题 各选项作答人数占比图")
                align(AAChartAlignType.Center)
                verticalAlign(AAChartVerticalAlignType.Bottom)
            }
        }

![QQ图片20220829142448](https://user-images.githubusercontent.com/49900392/187136400-eb7ad524-b2cd-4872-9c3e-48809a4f26fb.jpg)
