### ISSUE TITLE
请教一下大佬，如何显示全部dataLabel

### ISSUE THREAD

**Issue by GrizzlyRen** [AAChartModel/AAChartCore-Kotlin#137]
![IMG_20220906_143426](https://user-images.githubusercontent.com/24470901/188563561-29c0b04e-c167-44c2-af12-bdbb50990cfa.jpg)
如图，写了一个条形图， AAChartType.Bar ，设置 dataLabelsEnabled(true)，但是有些条形显示了值，有些却没有，请问应该如何让所有条形都显示值

**Comment by AAChartModel** [comment]
试试 `AADataLabels` 的 `allowOverlap` 属性

**Comment by AAChartModel** [comment]
> 但是有些条形显示了值，有些却没有

这是 Highcharts 为了避免数据过多时文字重叠, 有意这样设计的.

**Comment by GrizzlyRen** [comment]
> 试试 `AADataLabels` 的 `allowOverlap` 属性

非常感谢，可以正常显示了
