### ISSUE TITLE
禁止view的点击事件无效

### ISSUE THREAD

**Issue by whokill** [AAChartModel/AAChartCore-Kotlin#138]
options跟model都设置了touchEventEnabled为false。但是一样的还是可以点击

**Comment by AAChartModel** [comment]
AAChartView 直接继承自 WebView, 参考:

* https://stackoverflow.com/questions/19223824/how-to-make-webview-clickable-false-and-true

**Comment by AAChartModel** [comment]
`touchEventEnabled`  是用来设置是否获取点击事件的回调用的, 不是用来禁用点击事件的.
