### ISSUE TITLE
关于自定义颜色

### ISSUE THREAD

**Issue by whokill** [AAChartModel/AAChartCore-Kotlin#139]
请问每一种图表类型的自定义颜色的属性都不一样吗？建议各种图表的使用属性使用可以更新在文档里面。谢谢

**Comment by AAChartModel** [comment]
> 请问每一种图表类型的自定义颜色的属性都不一样吗？

各类图表基本上都是通过 Colors 来设置自定义颜色的, 并没有什么不同.

**Comment by AAChartModel** [comment]
基本上重要的属性, 都有使用示例. 更详细的文档, 参考 Highcharts 官网:

* https://api.highcharts.com/highcharts  (英文官网 API)
* https://api.hcharts.cn/highcharts (中文官网 API)

**Comment by whokill** [comment]
val aaOptions = AAOptions()
            .colors(arrayOf("#f56d45", "#7dffc0", "#d11b5f", "#facd32", "#ffffa0", "#EA007B"))
            .touchEventEnabled(false)
        baseBinding.lineChart.aa_drawChartWithChartOptions(aaOptions)
这样设置无效

**Comment by AAChartModel** [comment]
折线图， 只有多组 series 的时候， colors 才起作用。

**Comment by whokill** [comment]
哦哦，好的。非常感谢

**Comment by AAChartModel** [comment]
你这样设置， 如果是为了让折线分段显示不容颜色的话， 参考此示例：
*  https://github.com/AAChartModel/AAChartKit/issues/1291
*  https://github.com/AAChartModel/AAChartKit/issues/1293
Kotlin 版本的设置, 与之类似.
