### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by kenniholm** [AAChartModel/AAChartCore-Kotlin#14]
The install guide is rather vague, i did what it said i dragged the AAInfographicsLib into my libs folder in app folder and all the assets into the assets folder i created in app/src/main.

But how do i call that library? I cant seem to import it with import com.aaChart etc etc.

Could you eloborate on how to install? 
Im a noob with manually installing, because im used to using compile in graddle.

Regards
Kenni

**Comment by cristi-cosulianu** [comment]
+1

**Comment by Liad0205** [comment]
1. Download the repository
2. Locate the mentioned lib folder and assets folder
3. Place assets folder at ./project_folder/app/src/main
4. Place the AA library folder at ./project_folder/app/src/main/java/android/organisation/app_name/

add implementation 'com.google.code.gson:gson:2.8.6' to your gradle 
and if needed also add mavenLocal()

Sync gradle and rebuild the project and there you have it, running as it should :)

**Comment by cristi-cosulianu** [comment]
Yep man, that was the thibg to do, thanks!!!
Maybe you should add this info in readme if you have time.
Have a nice day!

Sent from Yahoo Mail on Android 
 
  On Thu, 21 May 2020 at 18:53, Liad0205<notifications@github.com> wrote:   

   
   - Download the repository
   - Locate the mentioned lib folder and assets folder
   - Place assets folder at ./project_folder/app/src/main
   - Place the AA library folder at ./project_folder/app/src/main/java/android/organisation/app_name/

add implementation 'com.google.code.gson:gson:2.8.6' to your gradle
and if needed also add mavenLocal()

Sync gradle and rebuild the project and there you have it, running as it should :)

**Comment by Liad0205** [comment]
Sure thing, glad I could help!

**Comment by AAChartModel** [comment]
## Installation


### Gradle


#### Step 1. Add the JitPack repository to your build file

Add it in your root build.gradle at the end of repositories:

```groovy
	allprojects {
		repositories {
			...
			maven { url 'https://www.jitpack.io' }
		}
	}
```
	
#### Step 2. Add the dependency

```groovy
	dependencies {
	        implementation 'com.github.AAChartModel:AAChartCore-Kotlin:-SNAPSHOT'
	}
```

You're all set, enjoy!
