### ISSUE TITLE
图表无法在BottomSheetDialog上显示

### ISSUE THREAD

**Issue by wangtingshun** [AAChartModel/AAChartCore-Kotlin#142]
以下是我的代码截图
![image](https://user-images.githubusercontent.com/38687493/192229635-7815db16-02a2-4693-9603-6357722cb6b8.png)
![image](https://user-images.githubusercontent.com/38687493/192229078-7801c14f-e746-48cb-94cd-a59241c37dd4.png)
![image](https://user-images.githubusercontent.com/38687493/192229361-b7b8f535-0c66-4308-acc1-1c7fa576a4a3.png)
![image](https://user-images.githubusercontent.com/38687493/192229526-f3f796cd-4493-4fb7-961c-ae7ab730a0af.png)

**Comment by AAChartModel** [comment]
BottomSheetDialog 没有使用过, 不太清楚是怎么回事. 不过你可以测试一下 WebView 是否能够在BottomSheetDialog上正常使用.  因为 AAChartView 是继承自 WebView 的. 理论上只要 WebView 能够在B ottomSheetDialog 上正常工作, AAChartView 就应该也可以.

**Comment by wangtingshun** [comment]
可以显示了,前提是BottomSheetDialog要设置固定高度。
