### ISSUE TITLE
label's Color

### ISSUE THREAD

**Issue by wangtingshun** [AAChartModel/AAChartCore-Kotlin#143]
![WX20221010-112630@2x](https://user-images.githubusercontent.com/38687493/194795604-1a44acd3-d961-4915-b1b4-2220683d0225.png)

**Comment by AAChartModel** [comment]
参考:
* https://github.com/AAChartModel/AAChartKit-Swift/issues/404

**Comment by wangtingshun** [comment]
> 参考:
> 
> * [label's colors   AAChartKit-Swift#404](https://github.com/AAChartModel/AAChartKit-Swift/issues/404)
Android版的没有formatter方法，参考ios方案后，饼状图不显示了。
![image](https://user-images.githubusercontent.com/38687493/194835772-652581ad-805e-46cd-88c8-67a6988ac5b3.png)

**Comment by AAChartModel** [comment]
Kotlin 版本的配置方式, 参考此次提交:
* https://github.com/AAChartModel/AAChartCore-Kotlin/commit/00cd1bfeec841f9237cd3617d5e6750d2c1a2852
