### ISSUE TITLE
远程仓库下载失败

### ISSUE THREAD

**Issue by whokill** [AAChartModel/AAChartCore-Kotlin#146]
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find AAChartCore-Kotlin--SNAPSHOT.jar (com.github.AAChartModel:AAChartCore-Kotlin:-SNAPSHOT:7.1.0-gebbe3db-143).

**Comment by AAChartModel** [comment]
像下面这样, 指定版本`7.1.0`试试看呢?

```groovy
	dependencies {
	        implementation 'com.github.AAChartModel:AAChartCore-Kotlin:7.1.0'
	}
```

**Comment by whokill** [comment]
7.1.0也不行。而且有的方法没有

**Comment by m5314** [comment]
同样的问题，拉不下snapshot了，7.1.0可以拉下来但一些方法接口跟原来不一样

**Comment by mufaith** [comment]
Failed to transform AAChartCore-Kotlin--SNAPSHOT.jar (com.github.AAChartModel:AAChartCore-Kotlin:-SNAPSHOT:7.1.0-gebbe3db-143) 
@AAChartModel

**Comment by AAChartModel** [comment]
> 同样的问题，拉不下snapshot了，7.1.0可以拉下来但一些方法接口跟原来不一样

新增了一个 `7.2.0` 版本的标签, 试试看可否下载更新:

```groovy
	dependencies {
	        implementation 'com.github.AAChartModel:AAChartCore-Kotlin:7.2.0'
	}
```

**Comment by whokill** [comment]
为啥snapshot不能用了，jitpack仓库上的状态就是get it 了的嘛。7.2.0是可以用的

**Comment by AAChartModel** [comment]
> 为啥snapshot不能用了，jitpack仓库上的状态就是get it 了的嘛。7.2.0是可以用的

<img width="637" alt="截屏2022-11-15 13 51 54" src="https://user-images.githubusercontent.com/16357599/201837028-2167bfac-a38c-4ad6-86cb-36db37e0f3a4.png">

**Comment by AAChartModel** [comment]
> 为啥snapshot不能用了，jitpack仓库上的状态就是get it 了的嘛。7.2.0是可以用的

不太清楚 jitpack 出了什么状况, 不过如果` 7.2.0` 可以用了, 那就算是没有问题了. 因为目前 `7.2.0` 的内容和 `snapshot` 是完全相同的

**Comment by whokill** [comment]
ok大佬

**Comment by whokill** [comment]
考虑放到mavenCentral上面去吗？

**Comment by AAChartModel** [comment]
鉴于 Jitpack 服务稳定性堪忧, 后面有机会会在 MavenCentral 上发布.
