### ISSUE TITLE
Documentation for range segmentation Band

### ISSUE THREAD

**Issue by ahudej** [AAChartModel/AAChartCore-Kotlin#148]
"chart with value range segmentation bands 🎀 " - like mentioned in the ReadMe Section, it should be possible to divide the chart into colorful segments.

Is there anywhere the documentation to do so?

**Comment by AAChartModel** [comment]
* https://api.highcharts.com/highcharts/xAxis.plotBands
* https://api.highcharts.com/highcharts/yAxis.plotBands
