### ISSUE TITLE
Received status code 521 from server

### ISSUE THREAD

**Issue by VijayRathodM** [AAChartModel/AAChartCore-Kotlin#152]
I implement gradle following: 
 **implementation 'com.github.AAChartModel:AAChartCore-Kotlin:-SNAPSHOT'**

  **repositories {
     maven { url 'https://www.jitpack.io' }
 }**

Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.github.AAChartModel:AAChartCore-Kotlin:-SNAPSHOT:7.2.0-g282fcda-3
Could not get resource 'https://jitpack.io/com/github/AAChartModel/AAChartCore-Kotlin/-SNAPSHOT/AAChartCore-Kotlin--7.2.0-g282fcda-3.aar'.
Could not HEAD 'https://jitpack.io/com/github/AAChartModel/AAChartCore-Kotlin/-SNAPSHOT/AAChartCore-Kotlin--7.2.0-g282fcda-3.aar'. Received status code 521 from server:

**Comment by Hilal-Anwar** [comment]
The same thing was happening with me also , but after restarting android studio it worked.

**Comment by Dracilem** [comment]
same problem, but I restart ide it still can not work

**Comment by dreamyt** [comment]
> same problem, but I restart ide it still can not work

same problem

**Comment by Tobeyr1** [comment]
The same thing was happening with me also

**Comment by VijayRathodM** [comment]
I have already downloaded this file and add manually

**[AAChartCore-Kotlin.zip](https://github.com/AAChartModel/AAChartCore-Kotlin/files/10291932/AAChartCore-Kotlin.zip)**

**Comment by Hilal-Anwar** [comment]
same with me also.

> The same thing was happening with me also,But when you try to run it multiple times and enable the proxy, you can succeed

same with me also.

**Comment by VijayRathodM** [comment]
thanks for all your suggetion now working fine

**Comment by ketzalv** [comment]
Hi, I have the same problem, i found a lastest version on the Jitpack web and replace -SNAPSHOT for the lastest release version
replace
`implementation 'com.github.AAChartModel:AAChartCore-Kotlin:-SNAPSHOT'
`
for
`implementation 'com.github.AAChartModel:AAChartCore-Kotlin:7.2.0'
`
https://jitpack.io/#AAChartModel/AAChartCore-Kotlin/7.2.0

**Comment by ketzalv** [comment]
https://jitpack.io/#AAChartModel/AAChartCore-Kotlin

when i find the -SNAPSHOT version return file not found
<img width="949" alt="Screen Shot 2022-12-26 at 18 14 07" src="https://user-images.githubusercontent.com/11669054/209589839-bd8f7677-0b02-460d-8cef-6057b87cee9c.png">
<img width="341" alt="Screen Shot 2022-12-26 at 18 14 16" src="https://user-images.githubusercontent.com/11669054/209589852-858d66e1-5d49-4958-aa43-de40ff2b5c17.png">

**Comment by VijayRathodM** [comment]
@ketzalv thanks now working but it is possible to add aar file so download it
