### ISSUE TITLE
I want to change chartView direction

### ISSUE THREAD

**Issue by yunliangQ** [AAChartModel/AAChartCore-Kotlin#155]
now is ![image](https://resource-upload-server.oss-cn-beijing.aliyuncs.com/345.png)

I want 
![image](https://user-images.githubusercontent.com/21029599/212074570-67671e1e-470d-4219-9d37-f46886ad7ba7.png)

I want the bar to vertival

**Comment by yunliangQ** [comment]
How to change it?

**Comment by AAChartModel** [comment]
Why don't you use the column type chart?

**Comment by yunliangQ** [comment]
ok
