### ISSUE TITLE
Pie图中间显示文字怎么处理？

### ISSUE THREAD

**Issue by BLOODMAGEBURT** [AAChartModel/AAChartCore-Kotlin#159]
pie图中间空的，显示文字，怎么处理呢？类似下面的
![Uploading pie.jpeg…]()

**Comment by BLOODMAGEBURT** [comment]
![pie](https://user-images.githubusercontent.com/16059706/216239806-4c8ca789-50af-4d06-9b45-9e0164950474.jpeg)

**Comment by AAChartModel** [comment]
参考 OC 版本的相似问题:
* https://github.com/AAChartModel/AAChartKit/issues/1192

**Comment by BLOODMAGEBURT** [comment]
好的，谢谢
