### ISSUE TITLE
能放到Maven仓库吗？

### ISSUE THREAD

**Issue by IdyllicFish** [AAChartModel/AAChartCore-Kotlin#16]

**Comment by lydlovezjr** [comment]
同求

**Comment by AAChartModel** [comment]
## 安装

### 通过 Gradle 安装

#### Step 1. 添加 `JitPack 仓库支持` 到你的 `build` 文件中 

在**项目根目录**的 `build.gradle（注意：不是 app/build.gradle）` 中添加对 `JitPack` 的支持：

```groovy
	allprojects {
		repositories {
			...
			maven { url 'https://www.jitpack.io' }
		}
	}
```
	
#### Step 2. 添加 `AAChartCore-Kotlin(AAInfographics)` 依赖

```groovy
	dependencies {
	        implementation 'com.github.AAChartModel:AAChartCore-Kotlin:-SNAPSHOT'
	}
```

更多详尽内容参见 README 文档
