### ISSUE TITLE
Areasplinerange chart ignores markerRadius

### ISSUE THREAD

**Issue by apollo1220** [AAChartModel/AAChartCore-Kotlin#170]
When using the Areasplinerange chart type, if you set the markerRadius to 0 (or any other value) it has no effect on the rendered chart. The same code works if using the Area chart type.

```
aaChartModel = AAChartModel()
            .chartType(AAChartType.Areasplinerange)
            .backgroundColor("#000000")
            .axesTextColor("#FFFFFF")
            .dataLabelsEnabled(false)
            .series(/**/)

aaChartModel.markerRadius = 0
val chart = view?.findViewById<AAChartView>(R.id.chart)
chart?.aa_drawChartWithChartModel(aaChartModel)
```

**Comment by AAChartModel** [comment]
It was fixed in this commit 
* https://github.com/AAChartModel/AAChartCore-Kotlin/commit/5554243c247bf57a73d133a414a3ce893ea82628

Update the AAChartCore-Kotlin to the latest content, the problem would be solved.
