### ISSUE TITLE
保存为bitmap或者image

### ISSUE THREAD

**Issue by GibsonLi0704** [AAChartModel/AAChartCore-Kotlin#171]
请问这个library 可以将aachartview的图保存成bitmap或者bytearray吗

**Comment by AAChartModel** [comment]
`AAChartView` 默认未添加此功能. 

实际上, 由于 `AAChartView` 继承自 `WebView`, 所以你可以自行添加转 `bitmap` 的方法.  

参考:

* https://juejin.cn/s/android%20webview%E6%88%AA%E5%9B%BE
