### ISSUE TITLE
如何把Y轴数值画到柱状图的末尾

### ISSUE THREAD

**Issue by MaxxxLeung** [AAChartModel/AAChartCore-Kotlin#172]
![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/29100435/4458711c-5e39-431b-9250-8c44e11ec7b4)

**Comment by MaxxxLeung** [comment]
val aaChartModel = setChartParams(
            "标题1",
            arrayListOf("x1", "x2", "x3", "x4", "x5", "x6"),
            arrayOf(
                AASeriesElement()
                    .name("y1")
                    .data(
                        arrayOf(50, 80, 90, 50, 10)
                    )
                    .dataLabels(
                        AADataLabels()
                            .enabled(true)
                    )
                ,
                AASeriesElement()
                    .name("y2")
                    .data(
                        arrayOf(100, 150, 90, 60, 100)
                    )
                    .dataLabels(
                        AADataLabels()
                            .enabled(false)
                    )
            ),
            500
        )
        aaChartModel.stacking = AAChartStackingType.Normal
        val aaOptions = aaChartModel.aa_toAAOptions()
        aaChartView.aa_drawChartWithChartOptions(aaOptions)

**Comment by MaxxxLeung** [comment]
stacking设置AAChartStackingType.False时会写在末尾，但同时我也需要柱子叠加为一条，因此设置为AAChartStackingType.Normal，但此时数值就会画在柱子里面，有没有什么配置能够解决这一问题？谢谢

**Comment by AAChartModel** [comment]
参考 iOS 版本的相似问题:

* https://github.com/AAChartModel/AAChartKit/issues/850

**Comment by AAChartModel** [comment]
调整 AADataLabels 的位置的相关属性如下:

```kotlin
class AADataLabels {
...
    var align: String? = null
    var inside: Boolean? = null
...
    var x: Number? = null
    var y: Number? = null
...
}
```

**Comment by AAChartModel** [comment]
参考在线文档:

* https://api.highcharts.com/highcharts/series.bar.dataLabels

**Comment by AAChartModel** [comment]
你这里应该只要将 `AADataLabels` 这样设置就可以了

```kotlin
       AADataLabels()
                    .align(AAChartAlignType.Right) //设置数据标签位置居右
```
