### ISSUE TITLE
为什么点击一个点 会把整个曲线都加粗了呢？ 可以点击的时候 不会加粗整个曲线，而只显示弹窗吗？

### ISSUE THREAD

**Issue by strongerzzx** [AAChartModel/AAChartCore-Kotlin#175]
这是一开始：[](url)
![normal](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/47743431/82cc4269-55db-418e-91d1-694e8330af80)
这s是点击后：
![click](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/47743431/4130af68-4211-4df8-9c6a-59a31fd07444)
这是创建的代码:

**Comment by strongerzzx** [comment]
fun customArearangeChartTooltip(): AAOptions {

        val gradientColorDic1 = AAGradientColor.linearGradient(
            AALinearGradientDirection.ToBottom, "rgba(215,243,209,1)", //DodgerBlue, alpha 透明度 1
            "rgba(215,243,209,0.1)"//DodgerBlue, alpha 透明度 0.1
        )

        val aaChartModel =
            AAChartModel()
//                .chartType(AAChartType.Area)
                .chartType(AAChartType.Areaspline)
                .categories(
                    arrayOf(
                        "Jan",
                        "Feb",
                        "Mar",
                        "Apr",
                        "May",
                        "Jun",
                        "July"
                    )
                )
                .dataLabelsEnabled(false)//是否显示值
                .markerRadius(4)
                .yAxisLineWidth(1)
                .markerSymbol(AAChartSymbolType.Circle)
                .legendEnabled(true)
                .touchEventEnabled(false)
                .series(
                    arrayOf(
                        AASeriesElement()
                            .threshold(50)
                            .data(
                                arrayOf(
                                    106.4,
                                    129.2,
                                    269.9,
                                    100.5,
                                    144.0,
                                    176.0,
                                    135.6
                                )
                            )
                            .lineWidth(1)
                            .color("rgba(103,194,58,1)")
                            .fillColor(gradientColorDic1)
                    )
                )


        val aaOptions = aaChartModel.aa_toAAOptions()

        //最大值和最小值的线
        aaOptions.yAxis(
            AAYAxis()
                .visible(true)
                .title(AATitle().text(""))
                .lineWidth(2)
                .plotLines(
                    arrayOf(
                        AAPlotLinesElement()
                            .value(250f)
                            .color("#DE6268")
                            .width(2)
                            .dashStyle(AAChartLineDashStyleType.Dash)
                            .label(
                                AALabel()
                            ),
                        AAPlotLinesElement()
                            .value(60f)
                            .color("#DE6268")
                            .width(2)
                            .dashStyle(AAChartLineDashStyleType.Dash)
                            .label(
                                AALabel()
                                    .useHTML(true)
                                    .textAlign(AAChartAlignType.Right)
                                    .x(0).y(2)
                                    .formatter(
                                        ("function () {\n" +
                                                "               return `<span style=\"padding: 2px 15px; display: block; color: red\">`+this.options.value+`</span>`\n" +
                                                "               }")
                                    )
                            )
                    )
                )
        )

        //点击的悬浮窗
        aaOptions.tooltip?.apply {
            useHTML(true).formatter(
                """
function () {
            var myPointOptions = this.points[0].point.options;
            var xValue = myPointOptions.x;
            var lowValue = myPointOptions.low;
            var highValue = myPointOptions.high;
            var titleStr = '🌕 this is my custom tooltip description text content <br>';
            var xValueStr = '🌖 this is x value  : ' + xValue + '<br>';
            var lowValueStr = ' 🌗 this is low value  : ' + lowValue + '<br>';
            var highValueStr = '🌘 this is high value : ' + highValue + '<br>';
            var tooltipDescStr =  titleStr + xValueStr + lowValueStr + highValueStr;
            
   
            
            return tooltipDescStr;
        }
                 """.trimIndent()
            ).backgroundColor("#000000")
                .borderColor("#000000")
                .style(
                    AAStyle()
                        .color("#FFD700")
                        .fontSize(12)
                )

        }
        return aaOptions
    }

**Comment by AAChartModel** [comment]
参考 **AAChartKit** 中的相同问题:
* https://github.com/AAChartModel/AAChartKit/issues/948
