### ISSUE TITLE
Faded issue on click of chart 

### ISSUE THREAD

**Issue by shruti-techindustan** [AAChartModel/AAChartCore-Kotlin#180]
When I click on Graph it becomes faded. I want to do some actions on click of graph. Is there any way to fix this issue. For reference I have also attached image.

<img width="279" alt="Screenshot 2023-07-14 at 12 23 47 PM" src="https://github.com/AAChartModel/AAChartCore-Kotlin/assets/25892859/42490512-6626-48ad-85f0-34f61a1b7da9">

**Comment by AAChartModel** [comment]
Refer the same issue of OC lang version

* https://github.com/AAChartModel/AAChartKit/issues/949

**Comment by shruti-techindustan** [comment]
I want to perform click also. If I will use touchEventEnabledSet as false then click not working. I want to perform click as well as faded issue fix. Is there any way to fix faded issue while cliking.

**Comment by AAChartModel** [comment]
You do not need to set the `touchEventEnabledSet`  be `false`.

The only key content is 

```objc
    aaOptions.plotOptions.series.states = AAStates.new
    .inactiveSet(AAInactive.new
                 .enabledSet(false));
```

* https://github.com/AAChartModel/AAChartKit/issues/949#issuecomment-662207526
