### ISSUE TITLE
折线图X轴显示不全，求大佬指教

### ISSUE THREAD

**Issue by BestDreams** [AAChartModel/AAChartCore-Kotlin#182]
折线图X轴显示不全，求大佬指教
![微信图片_20230717092540](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/24364957/d7de430f-c04e-4001-8999-1b24ae754df9)
![微信截图_20230717092655](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/24364957/1a811de3-5854-4d63-85af-2681fd670aec)

**Comment by AAChartModel** [comment]
参考:
* https://stackoverflow.com/questions/30935345/how-to-prevent-highcharts-from-shortening-labels-with-ellipsis

**Comment by BestDreams** [comment]
看了stackoverflow，弄好了，谢谢大佬，加下面一句即可
option.xAxis?.labels(AALabels().style(AAStyle().textOverflow("none")))
