### ISSUE TITLE
AAChartModel can't modified programmaticaly ?

### ISSUE THREAD

**Issue by IrvanWijayaSardam** [AAChartModel/AAChartCore-Kotlin#201]
Is it possible to modify AAChartModel without setting to the aaChartView ?

I want to update the label to false when a tooltip is shown
![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/43365154/452e8779-42d5-4f18-882d-c6b791a2a179)

i have already create the callback from javascript, but when it got triggered, it need to be set to the aaChartView to made change at the graph
![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/43365154/894d3347-9814-4109-a0e3-06092a4583b2)

this is the callback func
![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/43365154/35d26c87-ee1c-4f40-92d9-ac9dabe2cfe9)

**Comment by AAChartModel** [comment]
If you want to update `AAOptions` for `AAChartView`, you can try this method in the `AAChartView.java`:

```java
/// A common chart update function
/// (you can update any chart element) to open, close, delete, add, resize, reformat, etc. elements in the chart.
/// Refer to https://api.highcharts.com/highcharts#Chart.update
///
/// It should be noted that when updating the array configuration,
/// for example, when updating configuration attributes including arrays such as xAxis, yAxis, series, etc., the updated data will find existing objects based on id and update them. If no id is configured or passed If the id does not find the corresponding object, the first element of the array is updated. Please refer to this example for details.
///
/// In a responsive configuration, the response of the different rules responsive.rules is actually calling chart.update, and the updated content is configured in chartOptions.
///
/// - Parameter options: A configuration object for the new chart options as defined in the options section of the API.
/// - Parameter redraw: Whether to redraw after updating the chart, the default is true
  public  void aa_updateChartWithOptions(
            Object options,
            Boolean redraw
    ) {
        boolean isAAOptionsClass = options instanceof AAOptions;
        String finalOptionsMapStr;

        if (isAAOptionsClass) {
            String aaOptionsMapStr = new Gson().toJson(options);
            finalOptionsMapStr = aaOptionsMapStr;
        } else {
            String classNameStr = options.getClass().getSimpleName();
            classNameStr = classNameStr.replace("AA","");

            //convert fist character to be lowercase string
            String firstChar = classNameStr.substring(0,1);
            String lowercaseFirstStr = firstChar.toLowerCase();
            classNameStr = classNameStr.substring(1);
            String finalClassName = lowercaseFirstStr + classNameStr;

            Map<String, Object> finalOptionsMap = new HashMap();
            finalOptionsMap.put(finalClassName,options);

            String optionsStr = new Gson().toJson(finalOptionsMap);
            finalOptionsMapStr = optionsStr;
        }

        String javaScriptStr = "updateChart('" + finalOptionsMapStr + "','" + redraw + "')";
        this.safeEvaluateJavaScriptString(javaScriptStr);
    }
```

you can find some usage samples in the  `AAChartCore-Kotlin` demo. 

Refer to the API doc online:
* https://api.highcharts.com/highcharts#Chart.update

**Comment by IrvanWijayaSardam** [comment]
what's the version that you use ? because in version com.github.AAChartModel:AAChartCore-Kotlin:7.1.0 , the function still like this


![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/43365154/9205749f-c71d-457f-b671-5f66378a8b03)

**Comment by AAChartModel** [comment]
Apologies for the mistake, the code snippet I shared is from the **Java** version of `AAChartCore` library.

**Comment by AAChartModel** [comment]
In any case, these two codes functionally serve the same purpose, they merely differ in terms of language version.

**Comment by IrvanWijayaSardam** [comment]
i've change the version from 7.1.0 to 7.2.0, and the function aa_updateChartWithOptions seems working
![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/43365154/21d4e1e3-dbb4-4484-bd69-5c62f49b95b5)
i think there's some change in the function, but i have new issues , why the dataLabelsEnabled is still visible when i set to false ? and the tooltip is not showing, like the new aaChartModel not applied anything

![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/43365154/8dd65524-f350-4f47-8951-4a893a066ae7)

this is how do i apply it for the first time
![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/43365154/506c953f-1d13-4b9c-a3f9-1339ae1c4545)

**Comment by IrvanWijayaSardam** [comment]
in the config i set the tooltip to enabled, but the tooltip javascript now showing 
![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/43365154/15579572-1cf7-4ef4-b49f-cf008a58a769)
