### ISSUE TITLE
如何禁用图例的点击事件

### ISSUE THREAD

**Issue by wxhwan** [AAChartModel/AAChartCore-Kotlin#204]
不想要图表下边的图例的点击事件，请问如何禁用呢

**Comment by wxhwan** [comment]
> 不想要图表下边的图例的点击事件，请问如何禁用呢

**Comment by AAChartModel** [comment]
参考 `Swift` 版本的相同问题:
* https://github.com/AAChartModel/AAChartKit-Swift/issues/183
`Kotlin` 版本的做法与之类似.

**Comment by wxhwan** [comment]
这是来自QQ邮箱的假期自动回复邮件。已收到你的邮件

**Comment by AAChartModel** [comment]
饼图禁用图例点击事件的方式稍微特殊一点, 参考:
* https://github.com/AAChartModel/AAChartKit-Swift/issues/393

**Comment by wxhwan** [comment]
但是我用的是java版本的，是这么写吗
aaOptions.plotOptions.series.events = new AASeriesEvents().legendItemClick("false");

**Comment by AAChartModel** [comment]
`Java` 版本的写法:

```java
        //禁用图例点击事件
        aaOptions.plotOptions.series.events = new AASeriesEvents()
                .legendItemClick("function() { " +
                        "return false; " +
                        "}");
```


**demo** 中有相关示例, 下载运行查看即可.

**Comment by wxhwan** [comment]
点击了之后看起来是不会隐藏折线了，但是折线的颜色变浅了

**Comment by AAChartModel** [comment]
这个应该是 Highcharts 刻意的默认效果, 参考:
* https://github.com/AAChartModel/AAChartKit/issues/949

**Comment by AAChartModel** [comment]
> 点击了之后看起来是不会隐藏折线了，但是折线的颜色变浅了

参考 Swift 版本的相同问题:
* https://github.com/AAChartModel/AAChartKit-Swift/issues/300
