### ISSUE TITLE
使用yAxisMax = 220，但是画出来的图标却是400

### ISSUE THREAD

**Issue by ysh512** [AAChartModel/AAChartCore-Kotlin#205]
使用api，yAxisMax=220，画出来的图是y坐标最大值是400
怎么让y坐标最大值不自动更新，完全依赖api设置

**Comment by AAChartModel** [comment]
你的配置代码是什么样的? 麻烦贴出来我复现一下看看.

**Comment by ysh512** [comment]
val aaChartModel = AAChartModel.Builder(requireContext())
            .setChartType(AAChartType.Column)
            .setDataLabelsEnabled(false)
            .setBorderRadius(4F)
            .setLegendEnabled(false)
            .setTouchEventEnabled(true)
            .setSeries(
                AASeriesElement()
                    .name("")
                    .data(dataArray.toTypedArray()).               //里面最大值是154
                    .color(AAGradientColor.linearGradient("rgba(242,82,70,0.2)","rgba(242,82,70,1.0)"))   //柱状图渐变色
                    .borderWidth(2F)
                    .dataLabels(AADataLabels().enabled(true).verticalAlign(AAChartVerticalAlignType.Middle)
                        .x(0)
                        .y(-10)
                        .style(AAStyle.style("#333333",12,AAChartFontWeightType.Thin)))  //柱状图上面表示大小的文字
            )
            .setYAxisTitle("")
            .setYAxisMax(210 as Number)
            .build()

        aaChartModel.categories = categoryArray

        var aaOption = aaChartModel.aa_toAAOptions()

        val aaLabels = AALabels()
            .autoRotation(false)
            .style(AAStyle().fontSize(12).color("#999999"))  //坐标轴上文字颜色

        aaOption.xAxis?.apply {
            labels(aaLabels)
                .lineColor("#EEEEEE")
                .lineWidth(0.5)
        }
        aaOption.yAxis?.apply {
            minorGridLineColor("#EEEEEE")
                .minorGridLineWidth(0.5)
                .labels(aaLabels)
        }

        chartView.aa_drawChartWithChartOptions(aaOption)

**Comment by AAChartModel** [comment]
参考:

* https://www.highcharts.com/forum/viewtopic.php?t=34052

**Comment by AAChartModel** [comment]
```kotlin
fun forceYAxisMaxAndMinValue() : AAOptions {
        val aaChartModel = AAChartModel()
            .chartType(AAChartType.Column)
            .dataLabelsEnabled(false)
            .borderRadius(4F)
            .legendEnabled(false)
            .touchEventEnabled(true)
            .series(arrayOf(
                AASeriesElement()
                    .name("")
                    .data(arrayOf(149.9, 154, 106.4, 129.2, 144.0, 154, 135.6, 154, 154, 154, 95.6, 54.4)) //里面最大值是154
                    .color(AAGradientColor.linearGradient("rgba(242,82,70,0.2)","rgba(242,82,70,1.0)"))   //柱状图渐变色
                    .borderWidth(2F)
                    .dataLabels(AADataLabels()
                        .enabled(true)
                        .verticalAlign(AAChartVerticalAlignType.Middle)
                        .x(0)
                        .y(-10)
                        .style(AAStyle.style("#333333",12,AAChartFontWeightType.Thin)))  //柱状图上面表示大小的文字
            ))
            .yAxisTitle("")
            .yAxisMax(210 as Number)

        val aaOptions = aaChartModel.aa_toAAOptions()

        val aaLabels = AALabels()
            .autoRotation(false)
            .style(AAStyle().fontSize(12).color("#999999"))  //坐标轴上文字颜色

        aaOptions.xAxis?.apply {
            labels(aaLabels)
                .lineColor("#EEEEEE")
                .lineWidth(0.5)
        }
        aaOptions.yAxis?.apply {
            minorGridLineColor("#EEEEEE")
                .minorGridLineWidth(0.5)
                .labels(aaLabels)
                .startOnTick(false)//关键内容
                .endOnTick(false)//关键内容
        }
        return aaOptions
    }
```

如上配置 `AAOptions` 即可.

**Comment by AAChartModel** [comment]
更新 `AAChartCore-Kotlin` 至最新内容, 即可使用为 `AAYAxis` 最新添加的

```kotlin
    var endOnTick: Boolean? = null //Whether to force the axis to end on a tick. Use this option with the maxPadding option to control the axis end. This option is always disabled, when panning type is either y or xy. Defaults to true.

    fun endOnTick(prop: Boolean?): AAYAxis {
        endOnTick = prop
        return this
    }
```

`endOnTick` 属性和设置方法.

详细内容, 请参考在线文档:
* http://api.highcharts.com/highcharts#yAxis.startOnTick
* http://api.highcharts.com/highcharts#yAxis.endOnTick
