### ISSUE TITLE
图表无法左右滑动

### ISSUE THREAD

**Issue by gstory0404** [AAChartModel/AAChartCore-Kotlin#206]
当设置.touchEventEnabled(true)后，图表无法左右滑动，只能在X轴label上滑动

**Comment by AAChartModel** [comment]
图表默认就是不能上下左右滑动的吧, 和这个 `.touchEventEnabled(true)`应该没什么关系, `touchEventEnabled`只是用来设置是否需要获取用户对图表的点击事件回调用的.
