### ISSUE TITLE
How to custom yAxis value

### ISSUE THREAD

**Issue by mfrizki1** [AAChartModel/AAChartCore-Kotlin#210]
How to custom yAxis value?

Thanks

![image](https://github.com/AAChartModel/AAChartCore-Kotlin/assets/30206793/c59517da-6d35-4303-8d75-856b4ac31b4b)

**Comment by AAChartModel** [comment]
Refer to:

* [format:](https://api.highcharts.com/highcharts/yAxis.labels.format)undefined
* [formatter:](https://api.highcharts.com/highcharts/yAxis.labels.formatter)undefined

**Comment by AAChartModel** [comment]
Refert to:
* https://github.com/AAChartModel/AAChartKit/issues/1330

You can find the same code of **Kotlin** version in the demo.
