### ISSUE TITLE
自定义图例的问题

### ISSUE THREAD

**Issue by MonkeyNino** [AAChartModel/AAChartCore-Kotlin#216]
根据需求，需要能展示完全在底部滚动的图例，所以可能需要使用原生自定义，想问下1.安卓有自定义的图例的点击事件或方法么，看iOS是有的，2.对于原生调用，有相关的案例或者文档么

**Comment by MonkeyNino** [comment]
另外，饼图设置不同 宽高后，绘制并没有自适应
![image](https://github.com/user-attachments/assets/110d7542-005a-4ee7-8edf-894d1450743b)
我是直接修改了contentHeight的高度

**Comment by AAChartModel** [comment]
>

安卓版本的示例如下:

```kotlin

    //https://bbs.hcharts.cn/article-109-1.html
    //图表自带的图例点击事件是：
    //点击某个显示/隐藏的图例，该图例对应的serie就隐藏/显示。
    //个人觉得不合理，正常来说，有多条折线(或其他类型的图表)，点击某个图例是想只看该图例对应的数据；
    //于是修改了图例点击事件。
    //
    //实现的效果是(以折线图为例)：
    //1. 当某条折线隐藏时，点击该折线的图例 --> 该折线显示；
    //2. 当全部折线都显示时，点击某个图例 --> 该图例对应的折线显示，其他折线均隐藏；
    //3. 当只有一条折线显示时，点击该折线的图例 --> 全部折线均显示；
    //4. 其他情况，按默认处理：
    //显示 --> 隐藏；
    //隐藏 --> 显示；
    //Customized legengItemClick Event online: http://code.hcharts.cn/rencht/hhhhLv/share
    fun customLegendItemClickEvent(): AAOptions {
        val aaChartModel = AAChartModel()
            .chartType(AAChartType.Column)
            .stacking(AAChartStackingType.Normal)
            .colorsTheme(arrayOf("#fe117c", "#ffc069", "#06caf4", "#7dffc0")) //设置主题颜色数组
            .markerRadius(0)
            .series(arrayOf(
                AASeriesElement()
                    .name("Tokyo")
                    .data(arrayOf(7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6)),
                AASeriesElement()
                    .name("NewYork")
                    .data(arrayOf(0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5)),
                AASeriesElement()
                    .name("London")
                    .data(arrayOf(0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0)),
                AASeriesElement()
                    .name("Berlin")
                    .data(arrayOf(3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8))))

        val aaOptions = aaChartModel.aa_toAAOptions()

        aaOptions.legend?.apply {
            enabled(true)
            .align(AAChartAlignType.Right) //设置图例位于水平方向上的右侧
            .layout(AAChartLayoutType.Vertical) //设置图例排列方式为垂直排布
            .verticalAlign(AAChartVerticalAlignType.Top) //设置图例位于竖直方向上的顶部
        }

        //自定义图例点击事件
        aaOptions.plotOptions?.series?.events = AASeriesEvents()
            .legendItemClick(
                """function(event) {
        function getVisibleMode(series, serieName) {
            var allVisible = true;
            var allHidden = true;
            for (var i = 0; i < series.length; i++) {
                if (series[i].name == serieName)
                    continue;
                allVisible &= series[i].visible;
                allHidden &= (!series[i].visible);
            }
            if (allVisible && !allHidden)
                return 'all-visible';
            if (allHidden && !allVisible)
                return 'all-hidden';
            return 'other-cases';
        }
        
        var series = this.chart.series;
        var mode = getVisibleMode(series, this.name);
        var enableDefault = false;
        if (!this.visible) {
            enableDefault = true;
        }
        else if (mode == 'all-visible') {
            var seriesLength = series.length;
            for (var i = 0; i < seriesLength; i++) {
                var serie = series[i];
                serie.hide();
            }
            this.show();
        }
        else if (mode == 'all-hidden') {
            var seriesLength = series.length;
            for (var i = 0; i < seriesLength; i++) {
                var serie = series[i];
                serie.show();
            }
        }
        else {
            enableDefault = true;
        }
        return enableDefault;
    }"""
            )
        return aaOptions
    }
```

你可以在 **demo** 中找到此示例.

**Comment by AAChartModel** [comment]
> 2.对于原生调用，有相关的案例或者文档么

案例 1
======

`AAChartView` 的下面这个方法:

```kotlin
 fun aa_onlyRefreshTheChartDataWithChartOptionsSeriesArray(
        seriesElementsArr: Array<AASeriesElement>,
        animation: Boolean
    ) {
        val seriesArr = Gson().toJson(seriesElementsArr)
        val javaScriptStr = "onlyRefreshTheChartDataWithSeries('$seriesArr','$animation')"
        safeEvaluateJavaScriptString(javaScriptStr)
    }
```
其实调用的是 JS 的这段代码:

```js
function onlyRefreshTheChartDataWithSeries(receivedSeries, animation) {
    var receivedSeriesArr = JSON.parse(receivedSeries);
    var seriesArrLength = receivedSeriesArr.length;
    for (var i = 0; i < seriesArrLength; i++) {
        var receivedSeriesElementData = receivedSeriesArr[i].data;
        // 获取series
        var seriesElement = aaGlobalChart.series[i];
        // 执行只刷新数据的函数
        seriesElement.setData(receivedSeriesElementData, false);
    }

    var animationBool = (animation == "true") ? true:false;
    aaGlobalChart.redraw(animationBool);
}
```

案例 2
======
AAChartView 的这个方法:

```kotlin
 fun aa_updateChartWithOptions(
        options: Any,
        redraw: Boolean
    ) {
        val isAAOptionsClass = options is AAOptions
        val finalOptionsMapStr: String
        if (isAAOptionsClass) {
            val aaOptionsMapStr = Gson().toJson(options)
            finalOptionsMapStr = aaOptionsMapStr
        } else {
            var classNameStr = options.javaClass.simpleName
            classNameStr = classNameStr.replace("AA", "")

            //convert fist character to be lowercase string
            val firstChar = classNameStr.substring(0, 1)
            val lowercaseFirstStr = firstChar.toLowerCase(Locale.ROOT)
            classNameStr = classNameStr.substring(1)
            val finalClassName = lowercaseFirstStr + classNameStr
            val finalOptionsMap = HashMap<String, Any>()
            finalOptionsMap[finalClassName] = options
            val optionsStr = Gson().toJson(finalOptionsMap)
            finalOptionsMapStr = optionsStr
        }
        val javaScriptStr = "updateChart('$finalOptionsMapStr','$redraw')"
        safeEvaluateJavaScriptString(javaScriptStr)
    }
```

其实调用的是 JS 的这段代码:

```js
function updateChart(optionsStr, redraw) {
    var options = JSON.parse(optionsStr);
    aaGlobalChart.update(options,redraw);
}
```

在 **demo** 中, 你也都能够找到相关使用示例.

**Comment by AAChartModel** [comment]
在 `AAChartView.html `文件中, 你能发现这段代码:

```html
<div id="container" style="width:100%; height: 100%;"></div>
```

这说明我本来就已经将绘制图表的容器 `div` 标签的宽高, ,默认设置为百分百填充 `AAChartView` 了.

**Comment by MonkeyNino** [comment]
> 在 `AAChartView.html `文件中, 你能发现这段代码:
> 
> ```
> <div id="container" style="width:100%; height: 100%;"></div>
> ```
> 
> 这说明我本来就已经将绘制图表的容器 `div` 标签的宽高, ,默认设置为百分百填充 `AAChartView` 了.

那对于饼图。需要如何在改变面板的情况下，让饼图去适应。当我把面板高度修改小后。饼图并没有跟着变小，甚至占用了图例的位置

**Comment by AAChartModel** [comment]
> 饼图并没有跟着变小，甚至占用了图例的位置

你是不是设置了饼图自身的 `size` 了? 你把 `size` 相关的内容删除再看看效果呢?

**Comment by MonkeyNino** [comment]
> ```kotlin
> aa_onlyRefreshTheChartDataWithChartOptionsSeriesArray
> ```

我可以理解为AAChartView中的contentWidth和contentHeight么，其他的没有设置宽高

**Comment by MonkeyNino** [comment]
> > 2.对于原生调用，有相关的案例或者文档么
> 
> # 案例 1
> `AAChartView` 的下面这个方法:
> 
> ```kotlin
>  fun aa_onlyRefreshTheChartDataWithChartOptionsSeriesArray(
>         seriesElementsArr: Array<AASeriesElement>,
>         animation: Boolean
>     ) {
>         val seriesArr = Gson().toJson(seriesElementsArr)
>         val javaScriptStr = "onlyRefreshTheChartDataWithSeries('$seriesArr','$animation')"
>         safeEvaluateJavaScriptString(javaScriptStr)
>     }
> ```
> 
> 其实调用的是 JS 的这段代码:
> 
> ```js
> function onlyRefreshTheChartDataWithSeries(receivedSeries, animation) {
>     var receivedSeriesArr = JSON.parse(receivedSeries);
>     var seriesArrLength = receivedSeriesArr.length;
>     for (var i = 0; i < seriesArrLength; i++) {
>         var receivedSeriesElementData = receivedSeriesArr[i].data;
>         // 获取series
>         var seriesElement = aaGlobalChart.series[i];
>         // 执行只刷新数据的函数
>         seriesElement.setData(receivedSeriesElementData, false);
>     }
> 
>     var animationBool = (animation == "true") ? true:false;
>     aaGlobalChart.redraw(animationBool);
> }
> ```
> 
> # 案例 2
> AAChartView 的这个方法:
> 
> ```kotlin
>  fun aa_updateChartWithOptions(
>         options: Any,
>         redraw: Boolean
>     ) {
>         val isAAOptionsClass = options is AAOptions
>         val finalOptionsMapStr: String
>         if (isAAOptionsClass) {
>             val aaOptionsMapStr = Gson().toJson(options)
>             finalOptionsMapStr = aaOptionsMapStr
>         } else {
>             var classNameStr = options.javaClass.simpleName
>             classNameStr = classNameStr.replace("AA", "")
> 
>             //convert fist character to be lowercase string
>             val firstChar = classNameStr.substring(0, 1)
>             val lowercaseFirstStr = firstChar.toLowerCase(Locale.ROOT)
>             classNameStr = classNameStr.substring(1)
>             val finalClassName = lowercaseFirstStr + classNameStr
>             val finalOptionsMap = HashMap<String, Any>()
>             finalOptionsMap[finalClassName] = options
>             val optionsStr = Gson().toJson(finalOptionsMap)
>             finalOptionsMapStr = optionsStr
>         }
>         val javaScriptStr = "updateChart('$finalOptionsMapStr','$redraw')"
>         safeEvaluateJavaScriptString(javaScriptStr)
>     }
> ```
> 
> 其实调用的是 JS 的这段代码:
> 
> ```js
> function updateChart(optionsStr, redraw) {
>     var options = JSON.parse(optionsStr);
>     aaGlobalChart.update(options,redraw);
> }
> ```
> 
> 在 **demo** 中, 你也都能够找到相关使用示例.

这个效果就是跟https://github.com/AAChartModel/AAChartKit/issues/1550一样的吧

**Comment by AAChartModel** [comment]
> 这个效果就是跟https://github.com/AAChartModel/AAChartKit/issues/1550 一样的吧

并非如此, 你所引用的
* https://github.com/AAChartModel/AAChartKit/issues/1550

这个 **issue** 对应的 **kotlin** 版本的是这段代码

```kotlin
  fun aa_showTheSeriesElementContent(elementIndex: Int) {
        val javaScriptStr = "showTheSeriesElementContentWithIndex('$elementIndex')"
        safeEvaluateJavaScriptString(javaScriptStr)
    }

    fun aa_hideTheSeriesElementContent(elementIndex: Int) {
        val javaScriptStr = "hideTheSeriesElementContentWithIndex('$elementIndex')"
        safeEvaluateJavaScriptString(javaScriptStr)
    }
```

不过我目前还没给 **kotlin** 版本的 **demo** 中, 添加这两个方法的使用示例.

**Comment by AAChartModel** [comment]
> 不过我目前还没给 kotlin 版本的 demo 中, 添加这两个方法的使用示例.

虽然为添加使用示例, 但是你用起来的话, 方法的效果应该和 **iOS** 版本的是一模一样的.

**Comment by MonkeyNino** [comment]
> ```kotlin
> aa_showTheSeriesElementContent
> ```

我使用了Java版本的demo修改饼图大小后也没有完全适配
![image](https://github.com/user-attachments/assets/1ff131a6-06c6-4331-a664-7d33a394a48c)
我开了布局边界，更清楚的看到面板变小了，但是饼图大小没有变化

**Comment by AAChartModel** [comment]
> > 饼图并没有跟着变小，甚至占用了图例的位置
> 
> 你是不是设置了饼图自身的 `size` 了? 你把 `size` 相关的内容删除再看看效果呢?

demo 中 size 相关的代码你确认删除了吗?

**Comment by MonkeyNino** [comment]
> > > 饼图并没有跟着变小，甚至占用了图例的位置
> > 
> > 
> > 你是不是设置了饼图自身的 `size` 了? 你把 `size` 相关的内容删除再看看效果呢?
> 
> **demo** 中设置饼图 `size` 相关的代码你确认删除了吗?

方便问下哪里是设置饼图size相关的么

**Comment by AAChartModel** [comment]
> 方便问下哪里是设置饼图 `size` 相关的么?
```java
 public static AAChartModel configurePieChart() {
        return new AAChartModel()
                .chartType(AAChartType.Pie)
                .backgroundColor("#ffffff")
                .title("LANGUAGE MARKET SHARES JANUARY,2020 TO MAY")
                .subtitle("virtual data")
                .dataLabelsEnabled(true)//是否直接显示扇形图数据
                .yAxisTitle("℃")
                .series(new AAPie[] {
                        new AAPie()
                                .name("Language market shares")
                                .innerSize("20%")
                                .size(150)
                                .dataLabels(new AADataLabels()
                                        .enabled(true)
                                        .useHTML(true)
                                        .distance(5)
                                        .format("<b>{point.name}</b>: <br> {point.percentage:.1f} %"))
                                .data(new Object[][] {
                                {"Java"  ,67},
                                {"Swift",999},
                                {"Python",83},
                                {"OC"    ,11},
                                {"Go"    ,30},
                        })
                });
    }
```

你把 demo 中的这段代码里的
```java
 .innerSize("20%")
 .size(150)
```
删了再试试效果.

**Comment by MonkeyNino** [comment]
> > 不过我目前还没给 kotlin 版本的 demo 中, 添加这两个方法的使用示例.
> 
> 虽然未添加使用示例, 但是你用起来的话, 方法的效果应该和 **iOS** 版本的是一模一样的.

饼图有对应的图例点击隐藏显示的方法么
