### ISSUE TITLE
Failed to resolve: com.github.AAChartModel:AAChartCore-Kotlin:7.2.1

### ISSUE THREAD

**Issue by hjf-codecrazy** [AAChartModel/AAChartCore-Kotlin#217]
maven { url 'https://www.jitpack.io' }

Failed to resolve: com.github.AAChartModel:AAChartCore-Kotlin:7.2.1

**Comment by hjf-codecrazy** [comment]
下载不了，不知道为啥？

**Comment by hjf-codecrazy** [comment]
目前暂时用这着 com.github.AAChartModel:AAChartCore-Kotlin:7.2.0

**Comment by ehuiz** [comment]
+1 ，7.2.1 和7.2.2都下载不了

**Comment by sanjacurcic** [comment]
+1

**Comment by grayankit** [comment]
Someone found out how to fix

**Comment by voronind-com** [comment]
> Someone found out how to fix

Guys above use 7.2.0 version, which also works for me.

**Comment by AAChartModel** [comment]
<img width="612" alt="截屏2024-10-22 19 39 24" src="https://github.com/user-attachments/assets/1f9a31b1-7cbc-4974-9007-07dded0439b7">


```groovy
dependencies {
    implementation 'com.github.AAChartModel:AAChartCore-Kotlin:7.2.3'
}
```

There were some compatibility issues before, but now it's fixed. Update to the latest version `7.2.3` please.
