### ISSUE TITLE
安装后无法运行

### ISSUE THREAD

**Issue by D10NGYANG** [AAChartModel/AAChartCore-Kotlin#22]
Cannot access class 'AAInfographicsLib.AAChartCreator.AAChartView'. Check your module classpath for missing or conflicting dependencies

**Comment by D10NGYANG** [comment]
![Uploading image.png…]()
我的文件放在这里正确吗

**Comment by D10NGYANG** [comment]
./ChartTest/app/src/main/java/android/organisation/com/dlong/charttest/AAInfographicsLib 这个路径正确吗？

**Comment by D10NGYANG** [comment]
找到问题了，移除Databinding就好了。希望你们能支持DataBinding.

**Comment by AAChartModel** [comment]
AAChartCore-Kotlin 现已支持 Gradle 导入 , 参见 #16
