### ISSUE TITLE
Jitpack build issue for 7.2.1

### ISSUE THREAD

**Issue by Avs-Pavan** [AAChartModel/AAChartCore-Kotlin#221]
Hi while working with version 7.2.1 earlier it's working fine.
But now the build is failing. I checked in Jitpack and the build failed for 7.2.1 in jitpack.
https://jitpack.io/com/github/AAChartModel/AAChartCore-Kotlin/7.2.1/build.log

> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.codehaus.groovy.modules.http-builder:http-builder:0.7.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom
       - https://jcenter.bintray.com/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom
       - https://plugins.gradle.org/m2/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom
     Required by:
         project : > com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.5
         
         
         BUILD FAILED in 853ms
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2024-10-02T14:48:11.535950001Z
Exit code: 0

⚠️ ERROR: No build artifacts found

**Comment by ketzalv** [comment]
Hello

I'm not sure why can't compile with the bintray plugin, but i think that the project need update the mechanism to upload the library to the repositories. If you only want to build the project to see the samples or the code you can apply a workaround to build follow the next steps

Remove this line in the gradle project level:
`        classpath(Libs.com_jfrog_bintray_gradle_bintray_plugin)
`

Remove this line in the :chart gradle module level
```
    dependencies {
        classpath(Libs.com_jfrog_bintray_gradle_bintray_plugin)
    }
```

Make project.

**Comment by AAChartModel** [comment]
Refer to same issue:
* https://github.com/AAChartModel/AAChartCore-Kotlin/issues/217
