### ISSUE TITLE
demo中限制AAChartView的高度，加载后 会自动滚动到最后一条

### ISSUE THREAD

**Issue by ehuiz** [AAChartModel/AAChartCore-Kotlin#227]
![image](https://github.com/user-attachments/assets/3a947188-56e4-4df8-ba0a-c38b23ae6f01)

![image](https://github.com/user-attachments/assets/3b3c03d2-b451-4e49-852a-bab8f1e45b61)

**Comment by ehuiz** [comment]
https://github.com/user-attachments/assets/8d503f34-f281-4df9-9c2b-171e2fd57d53

**Comment by AAChartModel** [comment]
```kotlin
  AAScrollablePlotArea()
                    .minWidth(3000)
                    .scrollPositionX(1f)
```

应该是这段代码的 `scrollPositionX(1f)` 产生的影响. 

参考:
 * https://api.highcharts.com/highcharts/chart.scrollablePlotArea.scrollPositionX
