### ISSUE TITLE
chart点击后会自动获取到焦点，而不失效

### ISSUE THREAD

**Issue by MonkeyNino** [AAChartModel/AAChartCore-Kotlin#231]
chart点击后会自动获取到焦点，而不失效
在点击其他控件的刷新时，会再次回到当前chart的点击处，
有什么方法可以避免这种情况

**Comment by AAChartModel** [comment]
> chart点击后会自动获取到焦点，而不失效

你这里所说的焦点, 指的是什么?

**Comment by MonkeyNino** [comment]
比如点击柱状图后，弹出了tooltip

**Comment by MonkeyNino** [comment]
有任何想法可以提供么

**Comment by AAChartModel** [comment]
* https://github.com/AAChartModel/AAChartKit-Swift/issues/506

你的需求应该和这个类似

**Comment by MonkeyNino** [comment]
也不是，我用的是原生的 aaOptions.tooltip，不是JS

**Comment by MonkeyNino** [comment]
我用其他方法解决了
