### ISSUE TITLE
X轴显示不全

### ISSUE THREAD

**Issue by MonkeyNino** [AAChartModel/AAChartCore-Kotlin#232]
X轴第一个数据显示不全，如果数据很多，比如超过15条时，第一个X轴数据显示不全

**Comment by MonkeyNino** [comment]
![企业微信截图_17313191624098](https://github.com/user-attachments/assets/561fbbc7-db4b-4f3d-99dd-58fb487a5463)

**Comment by AAChartModel** [comment]
这个问题在 Highcharts 中比较常见，我可以提供几种解决方案：

1. 调整 xAxis 的 offset 值：
```javascript
xAxis: {
    offset: 40, // 增加偏移量，让第一个标签有更多显示空间
}
```

2. 调整标签的位置和对齐方式：
```javascript
xAxis: {
    labels: {
        align: 'left',          // 文字左对齐
        x: 4,                   // 向右偏移
        style: {
            textOverflow: 'none' // 防止文字被截断
        }
    }
}
```

3. 如果是日期类型的数据，可以通过格式化来缩短显示：
```javascript
xAxis: {
    labels: {
        formatter: function() {
            return Highcharts.dateFormat('%m/%d', this.value);
        }
    }
}
```

4. 设置标签旋转角度：
```javascript
xAxis: {
    labels: {
        rotation: -45,    // 旋转角度
        align: 'right'    // 对齐方式
    }
}
```

5. 调整图表边距：
```javascript
chart: {
    marginLeft: 80,  // 增加左边距
    spacingLeft: 20  // 增加左侧空间
}
```

一般来说，组合使用以上方法可以解决大多数情况。比如这个比较完整的配置：

```javascript
chart: {
    marginLeft: 80
},
xAxis: {
    offset: 40,
    labels: {
        rotation: -45,
        align: 'right',
        x: 4,
        style: {
            textOverflow: 'none'
        }
    }
}
```

如果数据真的非常多，你还可以考虑：
1. 使用 scrollbar（滚动条）
2. 只显示部分标签（通过 labels.step 设置）
3. 使用响应式设计，在不同宽度下显示不同数量的标签

以上内容整理自在线 AI 工具.

参考文档:
* https://api.highcharts.com/highcharts/chart.marginLeft
* https://api.highcharts.com/highcharts/xAxis.offset
* https://api.highcharts.com/highcharts/xAxis.labels

**Comment by AAChartModel** [comment]
另外也可以 通过给第一个`X` 轴的第一个 `label` 文字添加空格的方式来间接实现此功能.

例如:
===

将原始的 categories 文字数组
```js
 [
        "2024 年 11 月 01 日",
        "2024 年 11 月 02 日",
        "2024 年 11 月 03 日",
        "2024 年 11 月 04 日",
        "2024 年 11 月 05 日",
        ...
        ...
        ...
    ]
```
  
改成如下内容  
```js
    [
        "&nbsp &nbsp &nbsp &nbsp 2024 年 11 月 01 日",
        "2024 年 11 月 02 日",
        "2024 年 11 月 03 日",
        "2024 年 11 月 04 日",
        "2024 年 11 月 05 日",
        ...
        ...
        ...
    ]
```

添加多个 `&nbsp` 来添加空格, 借以让 `X` 轴的第一个 `label` 文字向右偏移, 避免被遮挡.

PS:
===

> “&nbsp” 是 HTML 中的一个特殊字符实体, 代表“不间断空格”(Non-breaking space).

**Comment by MonkeyNino** [comment]
iOS同样会遮挡，但是在使用AAScrollablePlotArea后，会有回弹的效果：能在靠近Y轴的地方，更多的拉出空白区域。安卓去没有这个效果，有什么设置时需要我变动的么
AAScrollablePlotArea().scrollPositionX(0).minWidth(600).opacity(1f)
