### ISSUE TITLE
Again~X轴第一个数据显示不全

### ISSUE THREAD

**Issue by MonkeyNino** [AAChartModel/AAChartCore-Kotlin#235]
https://github.com/AAChartModel/AAChartCore-Kotlin/issues/232
中的解决方案不能完美解决第一个数据不显示的问题
1.offset会让X轴上所有的数据进行偏移，导致数据显示错乱
2.marginLeft是增加了Y轴与左边的距离，而不是Y轴与第一个数据之间的距离
3.增加&nbsp会让数据直接显示成"..."

正常情况下不会遮挡，但是我使用了滚动，且opacity设置为1，在安卓中Y轴会遮挡X轴第一个数据
iOS中其实也是遮挡的，但是他的scrollbar有回弹效果，能够更多的拉出遮挡的空白区域，显示被遮挡的数据
我的问题
1.在安卓中有什么属性能控制回弹效果么
2.是否有属性能增加Y轴与第一个数据之间的距离

**Comment by MonkeyNino** [comment]
或者我怎么在开始设置opacity设置为0，在滚动的时候设置为1么？

**Comment by AAChartModel** [comment]
> 1.在安卓中有什么属性能控制回弹效果么

这个我之前尝试找过方案, 包括各种 AI 工具的解决方法, 试了都不行. 暂时还没找到什么有效解决办法.

**Comment by AAChartModel** [comment]
> 2.是否有属性能增加Y轴与第一个数据之间的距离

参考:
* https://api.highcharts.com/highcharts/yAxis.offset

**Comment by AAChartModel** [comment]
> 或者我怎么在开始设置opacity设置为0，在滚动的时候设置为1么？

 参考:
* https://api.highcharts.com/highcharts/chart.scrollablePlotArea

**Highcharts** 未给 `scrollablePlotArea` 添加滚动事件的监听回调方法, 所以目前也做不了.

**Comment by MonkeyNino** [comment]
我通过修改minWidth来尽量控制X轴的显示

**Comment by MonkeyNino** [comment]
以上
