### ISSUE TITLE
漏斗图比例问题

### ISSUE THREAD

**Issue by MonkeyNino** [AAChartModel/AAChartCore-Kotlin#237]
漏斗图是否能设置每部分的比例为1：1，或者其他
现在最下面的太小了。数据在上面无法显示全
类似这种
![image](https://github.com/user-attachments/assets/be1ed5a8-f3ed-4825-81b2-f4ac40842b09)

**Comment by AAChartModel** [comment]
Highcharts 的漏斗图默认情况下，每个部分的高度与其数据值成正比。如果您希望数据值不是 1 比 1，但图表显示效果是 1 比 1，您需要使用 `y` 属性来控制每个部分的高度，而不是直接使用您的数据值。  您可以创建一个新的数组，其中 `y` 值都相同，并在 `data` 数组中存储实际值，以便在工具提示或数据标签中显示。

以下是一个示例，演示如何实现这一点：

```javascript
Highcharts.chart('container', {
    chart: {
        type: 'funnel'
    },
    title: {
        text: '销售漏斗'
    },
    plotOptions: {
        series: {
            dataLabels: {
                enabled: true,
                format: '<b>{point.name}</b> ({point.value:,.0f})', // 显示实际值
                softConnector: true
            },
             neckWidth: '30%',
            neckHeight: '25%',
            width: '80%'
        }
    },
    series: [{
        name: '用户',
        data: [
            {name: '访问网站', y: 1, value: 15654000}, // y 值相同，value 存储实际值
            {name: '下载', y: 1, value: 4064},
            {name: '请求价格表', y: 1, value: 1987},
            {name: '发送发票', y: 1, value: 976},
            {name: '完成', y: 1, value: 846}
        ]
    }]
});

```

在这个例子中，所有的 `y` 值都设置为 1，这将使漏斗图的每个部分高度相同。`value` 属性存储了实际数据值，并在 `dataLabels` 中使用 `{point.value}` 显示。[2](https://stackoverflow.com/questions/59636887/highcharts-dealing-with-small-values-in-funnel-chart)


**关键点:**

*  使用 `y` 属性控制漏斗图每个部分的高度。
*  使用另一个属性（例如 `value`）存储实际数据值。
*  在 `dataLabels` 或 `tooltip` 中使用该属性显示实际数据值。


这种方法可以确保漏斗图的每个部分高度相同，同时仍然能够显示实际数据值。  如果您需要根据实际数据值调整漏斗图的整体大小，可以使用 `width` 和 `height` 选项，或者 `neckWidth` 和 `neckHeight` 选项来调整颈部的大小。[1](https://highcharts.com/docs/chart-and-series-types/funnel-series)



PS:
=== 
以上内容由我整理自在线 AI 工具.

其中的关键内容就是:

```js
    series: [{
        name: '用户',
        data: [
            {name: '访问网站', y: 1, value: 15654000}, // y 值相同，value 存储实际值
            {name: '下载', y: 1, value: 4064},
            {name: '请求价格表', y: 1, value: 1987},
            {name: '发送发票', y: 1, value: 976},
            {name: '完成', y: 1, value: 846}
        ]
    }]
```

**Comment by AAChartModel** [comment]
绘制的最终图表结果如下:
======

![chart (1)](https://github.com/user-attachments/assets/9d215bd6-4130-41ea-bc4d-4bcc83408059)

**Comment by AAChartModel** [comment]
PS:
===

AI 提示词为:

> Highcharts, 漏斗图, 我是希望我的数据值不是 1 比 1, 但是图表显示效果是 1 比 1, 应该怎么做?

AI 工具为:
> Gimini 1.5 pro

**Comment by MonkeyNino** [comment]
目前完美解决~感谢
