### ISSUE TITLE
Bintray or Jitpack

### ISSUE THREAD

**Issue by GuilhE** [AAChartModel/AAChartCore-Kotlin#25]
Hello,
What's the reason behind "manually import", why not Bintray ou Jitpack support?

Thanks.

**Comment by GuilhE** [comment]
For those of you who can't wait for the PR to be accepted you can find the last version here: 

[![](https://jitpack.io/v/GuilhE/AAChartCore-Kotlin.svg)](https://jitpack.io/#GuilhE/AAChartCore-Kotlin)

**Comment by AAChartModel** [comment]
## Installation


### Gradle


#### Step 1. Add the JitPack repository to your build file

Add it in your root build.gradle at the end of repositories:

```groovy
	allprojects {
		repositories {
			...
			maven { url 'https://www.jitpack.io' }
		}
	}
```
	
#### Step 2. Add the dependency

```groovy
	dependencies {
	        implementation 'com.github.AAChartModel:AAChartCore-Kotlin:-SNAPSHOT'
	}
```

You're all set, enjoy!  More details refer to README
