### ISSUE TITLE
Licence Issue?

### ISSUE THREAD

**Issue by NellyNeppach** [AAChartModel/AAChartCore-Kotlin#31]
Can you explain why you can offer this software with the Apache License, while integrating Highcharts, which forbids commercial use?

**Comment by AAChartModel** [comment]
The AAChartCore-Kotlin wrapper is licensed under the FREE license.

However, please be aware that the Highcharts project itself, as well as Highmaps and Highstock, are only free for non-commercial use under the Creative Commons Attribution-NonCommercial license. Commercial use requires the purchase of a separate license. Pop over to Highcharts for more information.
