### ISSUE TITLE
Line chart, the starting point of x draw for each of the three sets of data is inconsistent, is it supported

### ISSUE THREAD

**Issue by byron-xie** [AAChartModel/AAChartCore-Kotlin#45]
Line chart, the starting point of x draw for each of the three sets of data is inconsistent, is it supported

**Comment by AAChartModel** [comment]
Can you show me a design drawing?

**Comment by byron-xie** [comment]
![Uploading image.png…]()

**Comment by byron-xie** [comment]
> Can you show me a design drawing?

![image](https://user-images.githubusercontent.com/29298219/105655896-fed36080-5efb-11eb-8de4-aba8f55e987b.png)
like this

**Comment by byron-xie** [comment]
Customize the position of the point. The two points X and Y are automatically connected. If there is no point in front, it will not be connected. Currently you only support starting from 0.

**Comment by byron-xie** [comment]
![image](https://user-images.githubusercontent.com/29298219/105656062-5bcf1680-5efc-11eb-93ab-61e7e9b1da98.png)

**Comment by byron-xie** [comment]
![image](https://user-images.githubusercontent.com/29298219/105656095-6db0b980-5efc-11eb-9d11-df12aa22a41b.png)

**Comment by byron-xie** [comment]
> Can you show me a design drawing?

Supports custom point position, if there is no point before, it will not be connected, if there is a bit of information, two points are connected

**Comment by byron-xie** [comment]
I found it and can support
    AASeriesElement element4 = new AASeriesElement()
                 .name("Berlin")
                 .data(new Object[][] {
                         {5, 6},
                         {9, 15},
                         {12, 24},
                 });
