### ISSUE TITLE
想咨询一下一些问题AAOption的使用方法

### ISSUE THREAD

**Issue by longzhitao** [AAChartModel/AAChartCore-Kotlin#46]
![image](https://user-images.githubusercontent.com/35566389/105143433-d384f600-5b36-11eb-84d0-b7ddc52a2617.png)
我这样设置最大值还是不变
![image](https://user-images.githubusercontent.com/35566389/105143681-2199f980-5b37-11eb-9143-50b49dc26fb7.png)

散点图或折线图的x轴是否能以时间序列展示
比如（"14:55", 11）, ("15:55", 12)这样子
十分感谢

**Comment by AAChartModel** [comment]
你试试直接将你的 AAChartModel 转换成 AAOptions,然后修改最大值最小值,最后调用`aa_drawChartWithChartOptions`

```kotlin
            val aaOptions = aaChartModel.aa_toAAOptions()

            aaOptions.xAxis
                ?.min(0f)
                ?.max(1440f)
                ?.tickInterval(360)
            
        aaChartView.aa_drawChartWithChartOptions(aaOptions)
```

看看是否有用

**Comment by longzhitao** [comment]
![image](https://user-images.githubusercontent.com/35566389/105164291-ed7f0280-5b4f-11eb-862e-c7b074b69c46.png)
![image](https://user-images.githubusercontent.com/35566389/105164317-f4a61080-5b4f-11eb-8506-17fb5e6b7bfb.png)
十分感谢  关于AAOptions的用法可以了，关于x轴时间序列我想办法将下面的categories改成在这样，但是只有第一个刻度显示正确，是不是用法用错了，麻烦您了

**Comment by AAChartModel** [comment]
Highcharts 理论上, 只要你 X 轴有多少个刻度, 你的 categories 数组就得要有多少个元素. 只有这样, X轴的刻度和categories 数组中的元素才能一一对应起来.

所以你现在的 X轴的刻度为 1440, 那么你的 X轴的categories 数组的元素就应该有 1440 个. 不过由于这 1440 个元素,实际上只要显示 5 个, 所以直接为categories 数组添加 1440 个元素就太傻帽了.

**Comment by AAChartModel** [comment]
好在 X轴和 Y轴都有一个formatter属性,支持通过 JavaScript 函数来格式化 categories 的文字内容.

参考 iOS 版本 AAChartKit 的issue https://github.com/AAChartModel/AAChartKit/issues/675

其中 这段内容 https://github.com/AAChartModel/AAChartKit/issues/675#issuecomment-512086265  对应的 kotlin 版本如下


1.配置AAOptions实例对象
```kotlin
         fun customYAxisLabels():AAOptions {
            val aaChartModel = AAChartModel()
                .chartType(AAChartType.Line)//图形类型
                .title("")//图表主标题
                .subtitle("")//图表副标题
                .markerSymbolStyle(AAChartSymbolStyleType.BorderBlank)//折线连接点样式为外边缘空白
                .dataLabelsEnabled(false)
                .colorsTheme(arrayOf("#04d69f", "#1e90ff", "#ef476f", "#ffd066"))
                .stacking(AAChartStackingType.Normal)
                .markerRadius(8f)
                .series(arrayOf(
                    AASeriesElement()
                    .name("Tokyo Hot")
                    .lineWidth(5.0f)
                    .fillOpacity(0.4f)
                    .data(arrayOf(29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4))))

            val aaYAxisLabels = AALabels()
                .formatter("""
function () {
        var yValue = this.value;
        if (yValue >= 200) {
            return "极佳";
        } else if (yValue >= 150 && yValue < 200) {
            return "非常棒";
        } else if (yValue >= 100 && yValue < 150) {
            return "相当棒";
        } else if (yValue >= 50 && yValue < 100) {
            return "还不错";
        } else {
            return "一般";
        }
    }
                """.trimIndent()
                )

            val aaOptions = aaChartModel.aa_toAAOptions()
            aaOptions.yAxis?.labels(aaYAxisLabels)

            return aaOptions
        }
```

2. 绘图效果

![image](https://user-images.githubusercontent.com/16357599/61344789-249e9480-a885-11e9-9f93-22303a611a0e.png)


AAChartCore-Kotlin 的 demo 中有此示例, 下载运行查看即可.

**Comment by AAChartModel** [comment]
Swift 版本的 AAChartKit-Swift 中的这个问题 https://github.com/AAChartModel/AAChartKit-Swift/issues/232

其中第二个示例Y轴也是固定的几个点, 作为你的参考示例是更适合的. 这个 issue 中的第二个示例对应的 kotlin 版本为:

# Sample 2

```kotlin
         fun customYAxisLabels2():AAOptions {
            val aaChartModel = AAChartModel()
                .chartType(AAChartType.Line)//图形类型
                .title("")//图表主标题
                .subtitle("")//图表副标题
                .markerSymbolStyle(AAChartSymbolStyleType.BorderBlank)//折线连接点样式为外边缘空白
                .dataLabelsEnabled(false)
                .colorsTheme(arrayOf("#04d69f", "#1e90ff", "#ef476f", "#ffd066"))
                .stacking(AAChartStackingType.Normal)
                .markerRadius(8f)
                .series(arrayOf(AASeriesElement()
                    .name("Tokyo Hot")
                    .lineWidth(5.0f)
                    .fillOpacity(0.4f)
                    .data(arrayOf(229.9, 771.5, 1106.4, 1129.2, 6644.0, 1176.0, 8835.6, 148.5, 8816.4, 6694.1, 7795.6, 9954.4))))

            val aaYAxisLabels = AALabels()
                .style(AAStyle()
                    .fontSize(10f)
                    .fontWeight(AAChartFontWeightType.Bold)
                    .color(AAColor.Gray))
                .formatter("""
function () {
        var yValue = this.value;
        if (yValue == 0) {
            return "0";
        } else if (yValue == 2500) {
            return "25%";
        } else if (yValue == 5000) {
            return "50%";
        } else if (yValue == 7500) {
            return "75%";
        } else if (yValue == 10000) {
            return "100%";
        }
    }
                """.trimIndent()
                )

            val aaOptions = aaChartModel.aa_toAAOptions()
            aaOptions.yAxis!!
                .opposite(true)
                .tickWidth(2f)
                .lineWidth(1.5f)//Y轴轴线颜色
                .lineColor(AAColor.LightGray)//Y轴轴线颜色
                .gridLineWidth(0f)//Y轴网格线宽度
                .tickPositions(arrayOf(0, 2500, 5000, 7500, 10000))
                .labels(aaYAxisLabels)

            return aaOptions
        }
```

## Final Chart content

<img width="100%" alt="截屏2020-08-10 下午5 40 09" src="https://user-images.githubusercontent.com/16357599/89769894-8c7ae980-db30-11ea-9842-21ee537d3a6c.png">

AAChartCore-Kotlin 的 demo 中也有此示例, 下载运行查看即可.

**Comment by AAChartModel** [comment]
关于 Y 轴的 labels 格式化属性的在线文档, 参考

1. `format` : https://api.highcharts.com/highcharts/yAxis.labels.format
1. `formatter` : https://api.highcharts.com/highcharts/yAxis.labels.formatter

**Comment by AAChartModel** [comment]
关于 X 轴的 labels 格式化属性的在线文档, 参考

1. `format` : https://api.highcharts.com/highcharts/xAxis.labels.format
1. `formatter` : https://api.highcharts.com/highcharts/xAxis.labels.formatter

**Comment by AAChartModel** [comment]
所以,参考以上所有内容, 回到你的问题:

           你试试直接:

             1. 将你的 AAChartModel 转换成 AAOptions,
             2. 然后修改最大值最小值,并且修改X轴的 labels 的 formatter 属性
             3. 最后调用`aa_drawChartWithChartOptions`

             ```kotlin
//1. 将你的 AAChartModel 转换成 AAOptions,
             val aaOptions = aaChartModel.aa_toAAOptions()

//2. 然后修改最大值最小值,并且修改X轴的 labels 的 formatter 属性
             aaOptions.xAxis
                 ?.min(0f)
                 ?.max(1440f)
                 ?.tickInterval(360)
                 ?.labels(AALabels()
                     .formatter("""
function () {
        var xValue = this.value;
        if (xValue == 0) {
            return "00:00";
        } else if (xValue == 360) {
            return "06:00";
        } else if (xValue == 720) {
            return "12:00";
        } else if (xValue == 1080) {
            return "18:00";
        } else if (xValue == 1440) {
            return "00:00";
        }
    }
                """.trimIndent()
                     ))

//3. 最后调用`aa_drawChartWithChartOptions`
             aaChartView.aa_drawChartWithChartOptions(aaOptions)
             ```

             看看是否有用

**Comment by AAChartModel** [comment]
Tips 附言: 

你后面提问题的时候,如果需要粘贴代码,请直接复制代码文本,并使用 markdown 语法(GitHub 的 issue 区默认支持 markdown 语法)使得代码高亮.不要像上面这样

![](https://user-images.githubusercontent.com/35566389/105143433-d384f600-5b36-11eb-84d0-b7ddc52a2617.png)

粘贴代码图片,这样加载速度慢不说, 同时不利于我复制粘贴代码,复现问题.

markdown 语法参考链接 https://www.jianshu.com/p/ebe52d2d468f

**Comment by longzhitao** [comment]
了解了， 修改labels的formatter可以实现这个效果，十分感谢，麻烦您了，后面提出提出问题我会注意复制代码文本

**Comment by AAChartModel** [comment]
tips附言: 

AAChartModel 的属性`markerSymbol`可以直接设置图表 `marker` 点的类型对所有 AASeriesElement 元素有效,就像下面这样设置即可

```kotlin
        aaChartModel
            .markerSymbol(AAChartSymbolType.Circle)
```

这样就不用重复对每个AASeriesElement 的 marker 属性都反复设置 `AAMarker().symbol("circle")`了

**Comment by longzhitao** [comment]
`   
 override fun chartViewDidFinishLoad(aaChartView: AAChartView) {
        tvBGValue.text = "AAAAA"
    }

      override fun chartViewMoveOverEventMessage(aaChartView: AAChartView, messageModel: AAMoveOverEventMessageModel) {
          tvBGValue.text = messageModel.y.toString()
      }
`

我实现了AAChartViewCallBack这个接口发现回调只有加载的接口回调过，查看源码点击事件没有z回调，是否要调用androidMethod这个接口，该如何实现用户点击事件。 程序效果如下 麻烦您了
![image](https://user-images.githubusercontent.com/35566389/105282012-55812780-5be8-11eb-84eb-b4e56ab6fe0c.png)
