### ISSUE TITLE
Inflating data from network array error

### ISSUE THREAD

**Issue by IvanDeLucasRog** [AAChartModel/AAChartCore-Kotlin#48]
Hi! Such the best charts library! But I´ve a problem when inflating data in AASeriesElement(). I want to inflate an array from firebase but it throws me an error: 
Type mismatch: inferred type is array<float> but array<any> was expected

Thanks a lot! Im a bit noob

**Comment by machinelv** [comment]
Hello, I also meet the same error now. Could you tell me how to solve it? Thanks a lot.
