### ISSUE TITLE
关闭Y轴markerSymbol会全部显示

### ISSUE THREAD

**Issue by cs9420** [AAChartModel/AAChartCore-Kotlin#60]
默认设置markerSymbol只有拖动会显示选中数据的markerSymbol，当我关闭`yAxisVisible(false)`之后，markerSymbol会全部显示出来，没看到有什么设置可以控制，想问一下如何解决，我不想markerSymbol全部显示出来。

这个是我还没有关闭Y轴或者Y轴title
![1](https://user-images.githubusercontent.com/25837928/110053550-98f8b500-7d94-11eb-8f49-50f6f85cd5d5.png)

当关闭Y轴或者Y轴title后
![2](https://user-images.githubusercontent.com/25837928/110053558-9dbd6900-7d94-11eb-9e96-e70fdd11b2f7.png)

**Comment by AAChartModel** [comment]
Highcharts 会根据图表的可显示空间大小,自动显示和隐藏 marker 标记点, 当关闭Y轴或者Y轴title后, 图表可显示空间变大了, 所以 marker 就全部显示出来了. 

1. 简单一点的, 你可以通过调整图表的 margin 来适当缩小图表的显示空间,进而隐藏 marker
2. 或者直接先隐藏 marker, 然后自定义手指滑动时的 marker 样式, 参考 iOS 版本的这个相同问题 https://github.com/AAChartModel/AAChartKit/issues/948

**Comment by AAChartModel** [comment]
> 简单一点的, 你可以通过调整图表的 margin 来适当缩小图表的显示空间,进而隐藏 marker

```kotlin
    var margin: Array<Float>? = null           //图表外边缘和绘图区域之间的边距
```

参考在线链接: https://api.highcharts.com.cn/highcharts#chart.margin

**Comment by cs9420** [comment]
好的 感谢
