### ISSUE TITLE
Turn off animation

### ISSUE THREAD

**Issue by shervinkoushan** [AAChartModel/AAChartCore-Kotlin#61]
How can this be done? Nice library, but it takes a while to load as it is. Using it in a RecyclerView

**Comment by shervinkoushan** [comment]
Any update on this @AAChartModel ?

The best would be to let us turn off animation altogether.

Alternatively, let us set the animation duration to 1 millisecond or something. But turning it off would be preferable

**Comment by JSPRKWAN** [comment]
agree.

**Comment by EugeneHoran** [comment]
Can we get this option implemented? animationType(AAChartAnimationType.NONE || nullable). While it is efficient on pre drawn views it is demanding on recycled views.

**Comment by AAChartModel** [comment]
Update AAChartCore-Kotlin to the latest content. then

```kotlin
        aaOptions.chart?.animation = false //turn off animation
```
