### ISSUE TITLE
去怎么去除饼图的折线？

### ISSUE THREAD

**Issue by wealive** [AAChartModel/AAChartCore-Kotlin#81]
哪个属性？文档不是很详细

**Comment by BaiMingxu** [comment]
您好，请问解决了么？我也遇到了这个问题

**Comment by 6YK5** [comment]
请问解决了吗,那个属性可以控制呢

**Comment by 6YK5** [comment]
已解决,伪代码如下
`aaOption.plotOption?.pie?.dataLabels(AADataLabels().enabled(false))`
不知道为什么,直接使用AAChartModel或者AASeriesElement的DataLabelsEnabled属性,并没有起作用,只有通过上面这样设置才会生效,不知道是我的设置方式不正确,还是这个库的BUG
