### ISSUE TITLE
折线图上的点，有时候会消失

### ISSUE THREAD

**Issue by kenneyLee** [AAChartModel/AAChartCore-Kotlin#82]
当连续两个x轴坐标差距过小时，折线上的点就都消失了，就剩下一根光秃秃的线。
![image](https://user-images.githubusercontent.com/1628572/121905943-36cd2a00-cd5d-11eb-814f-1cd9f3eea9d4.png)

如上图，当x轴坐标数据有0.0和0.8时，线上的点就都消失了（下图）。
![image](https://user-images.githubusercontent.com/1628572/121906170-6d0aa980-cd5d-11eb-8983-bbea55abdf23.png)

当我把0.8改成0.9时，线上的点又都显示出来了。
![image](https://user-images.githubusercontent.com/1628572/121906379-a6dbb000-cd5d-11eb-8448-dc4a77a44b2b.png)

这是为什么，我如何处理，才能让线上的点，无论在什么时候都显示出来。

**Comment by AAChartModel** [comment]
参考 https://stackoverflow.com/questions/13084849/how-to-always-show-the-plotline-in-highcharts

**Comment by kenneyLee** [comment]
> 参考 https://stackoverflow.com/questions/13084849/how-to-always-show-the-plotline-in-highcharts

直接加一个散点图，真是简单粗暴，但确实有效。
