### ISSUE TITLE
怎么可以设置x轴标签不旋转，然后换行？

### ISSUE THREAD

**Issue by pizhu** [AAChartModel/AAChartCore-Kotlin#89]
我设置了**AALabels.autoRotation(false)**并没有换行，虽然不旋转了，但没有换行，多出部分直接变成省略号了。

**Comment by AAChartModel** [comment]
轴标签没有自动换行的功能, 如果想要换行, 参考 https://github.com/AAChartModel/AAChartKit/issues/1201
