### ISSUE TITLE
滑动事件冲突

### ISSUE THREAD

**Issue by keyejxptwn** [AAChartModel/AAChartCore-Kotlin#91]
当处于ViewPager+Fragment+RecyclerView中时，图表事件滑动会受影响，能否将AAChartView 改成 open

**Comment by 314GM** [comment]
你解决了这个问题嘛？ @keyejxptwn

**Comment by 314GM** [comment]
@AAChartModel 你好👋，我应该如何解决这个问题

**Comment by 314GM** [comment]
我找到了解决方案！这是ViewPager2本身的问题
使用NestedScrollableHost包裹住AAChartView即可解决问题

`<NestedScrollableHost
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.github.aachartmodel.aainfographics.aachartcreator.AAChartView
        android:id="@+id/barChart"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</NestedScrollableHost>`

这是关于NestedScrollableHost的代码
[https://github.com/androidx/androidx/blob/androidx-main/viewpager2/integration-tests/testapp/src/main/java/androidx/viewpager2/integration/testapp/NestedScrollableHost.kt](url)
