### ISSUE TITLE
大佬，如何修改饼图每个扇形的颜色！

### ISSUE THREAD

**Issue by ShuaiXiu** [AAChartModel/AAChartCore-Kotlin#99]

**Comment by ShuaiXiu** [comment]
大佬，现在又遇到问题了，如何固定X轴刻度只显示六个，或者如何修改X轴刻度的数量




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartCore-Kotlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月28日(星期四) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartCore-Kotlin] 大佬，如何修改饼图每个扇形的颜色！ (Issue #99)





     fun configurePieChart(): AAChartModel {         return AAChartModel()             .chartType(AAChartType.Pie)             .backgroundColor("#ffffff")             .title("LANGUAGE MARKET SHARES JANUARY,2020 TO MAY")             .subtitle("virtual data")             .colorsTheme(arrayOf("#0c9674", "#7dffc0", "#d11b5f", "#facd32", "#ffffa0",))             .dataLabelsEnabled(true)//是否直接显示扇形图数据             .yAxisTitle("℃")             .series(arrayOf(                 AASeriesElement()                     .name("Language market shares")                     .data(arrayOf(                         arrayOf("Java",   67),                         arrayOf("Swift", 999),                         arrayOf("Python", 83),                         arrayOf("OC",     11),                         arrayOf("Go",     30)                     ))))     }
 
更改扇形颜色的关键属性
             .colorsTheme(arrayOf("#0c9674", "#7dffc0", "#d11b5f", "#facd32", "#ffffa0",))
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AAChartModel** [comment]
```swift
class AAXAxis {
...
...
    var tickInterval: Int? = null//x轴刻度点间隔数(设置每隔几个点显示一个 X轴的内容:
...
...
}
```

试试通过 AAXAxis 这个属性来控制 X轴刻度的数量

**Comment by ShuaiXiu** [comment]
感谢大佬的帮助




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "An ***@***.***&gt;; 
发送时间: 2021年11月12日(星期五) 中午1:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AAChartModel/AAChartCore-Kotlin] 大佬，如何修改饼图每个扇形的颜色！ (Issue #99)





 class AAXAxis { ... ...     var tickInterval: Int? = null//x轴刻度点间隔数(设置每隔几个点显示一个 X轴的内容: ... ... }
 
试试通过 AAXAxis 这个属性来控制 X轴刻度的数量
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShuaiXiu** [comment]
大佬
这个图标库有办法添加空数据吗？
就是有五条数据，我手动补到15条，然后界面上折现只显示五条。

**Comment by AAChartModel** [comment]
不太清楚你想要的图表是什么样子的, 有设计稿吗?

**Comment by ShuaiXiu** [comment]
大佬，你好，感谢回复

大概是这样子的，就是后台只返了五条数据，然后我手动添加了十条，数据给的0，就有了上图的直接降到0，想要的效果是只显示图中框的部分，后面是空着就行。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartCore-Kotlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartCore-Kotlin] 大佬，如何修改饼图每个扇形的颜色！ (Issue #99)





 
不太清楚你想要的图表是什么样子的, 有设计稿吗?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AAChartModel** [comment]
你的图片没有上传成功, 不过我猜你可能是需要这个

* https://github.com/AAChartModel/AAChartKit-Swift/issues/249

**Comment by ShuaiXiu** [comment]
大佬是这个，不过我使用的是Kotlin的库，没有看到NsNull这个方法




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartCore-Kotlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 下午4:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartCore-Kotlin] 大佬，如何修改饼图每个扇形的颜色！ (Issue #99)





 
你的图片没有上传成功, 不过我猜你可能是需要这个
  
AAChartModel/AAChartKit-Swift#249
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AAChartModel** [comment]
## kotlin 版本

```kotlin
    fun configureDiscontinuousDataChart(): AAChartModel {
        return AAChartModel()
            .chartType(AAChartType.Column)
            .title("Discontinuous Data Chart")
            .yAxisTitle("")
            .dataLabelsEnabled(true)
            .tooltipEnabled(true)
            .series(arrayOf(
                AASeriesElement()
                    .name("Tokyo")
                    .data(arrayOf(
                        arrayOf<Any?>(6.9, 9.5, 14.5, 18.2, 21.5, null, null, null, null, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6)))
                    .color(AAGradientColor.DeepSea)))
    }
```

也就是说, 直接使用 null 对象占位即可.  AAChartCore-Kotlin 的 demo 中由此示例, 运行查看即可.

**Comment by ShuaiXiu** [comment]
代码是这样设置的


数据是这个







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartCore-Kotlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartCore-Kotlin] 大佬，如何修改饼图每个扇形的颜色！ (Issue #99)





 
kotlin 版本
     fun configureDiscontinuousDataChart(): AAChartModel {         return AAChartModel()             .chartType(AAChartType.Column)             .title("Discontinuous Data Chart")             .yAxisTitle("")             .dataLabelsEnabled(true)             .tooltipEnabled(true)             .series(arrayOf(                 AASeriesElement()                     .name("Tokyo")                     .data(arrayOf(                         arrayOf<Any?&gt;(6.9, 9.5, 14.5, 18.2, 21.5, null, null, null, null, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6)))                     .color(AAGradientColor.DeepSea)))     }
 
也就是说, 直接使用 null 对象占位即可.  AAChartCore-Kotlin 的 demo 中由此示例, 运行查看即可.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShuaiXiu** [comment]
大佬，使用
fun configureDiscontinuousDataChart(): AAChartModel {         return AAChartModel()             .chartType(AAChartType.Column)             .title("Discontinuous Data Chart")             .yAxisTitle("")             .dataLabelsEnabled(true)             .tooltipEnabled(true)             .series(arrayOf(                 AASeriesElement()                     .name("Tokyo")                     .data(arrayOf(                         arrayOf<Any?&gt;(6.9, 9.5, 14.5, 18.2, 21.5, null, null, null, null, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6)))                     .color(AAGradientColor.DeepSea)))     }这串代码展示的也不是正常的，好像有bug




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartCore-Kotlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartCore-Kotlin] 大佬，如何修改饼图每个扇形的颜色！ (Issue #99)





 
kotlin 版本
     fun configureDiscontinuousDataChart(): AAChartModel {         return AAChartModel()             .chartType(AAChartType.Column)             .title("Discontinuous Data Chart")             .yAxisTitle("")             .dataLabelsEnabled(true)             .tooltipEnabled(true)             .series(arrayOf(                 AASeriesElement()                     .name("Tokyo")                     .data(arrayOf(                         arrayOf<Any?&gt;(6.9, 9.5, 14.5, 18.2, 21.5, null, null, null, null, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6)))                     .color(AAGradientColor.DeepSea)))     }
 
也就是说, 直接使用 null 对象占位即可.  AAChartCore-Kotlin 的 demo 中由此示例, 运行查看即可.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShuaiXiu** [comment]
AASeriesElement()                     .name("Tokyo")                     .data(arrayOf(                         arrayOf<Any?&gt;(6.9, 9.5, 14.5, 18.2, 21.5, null, null, null, null, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6)))                     .color(AAGradientColor.DeepSea))大佬，上述代码中data只传一个arrayOf()是可以正常绘制的，但是如果传arrayOf(arrayOf())就会出现绘制失败的问题，但是只传一个arrayOf()，他的值又是不能为空的，目前遇到了这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartCore-Kotlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartCore-Kotlin] 大佬，如何修改饼图每个扇形的颜色！ (Issue #99)





 
kotlin 版本
     fun configureDiscontinuousDataChart(): AAChartModel {         return AAChartModel()             .chartType(AAChartType.Column)             .title("Discontinuous Data Chart")             .yAxisTitle("")             .dataLabelsEnabled(true)             .tooltipEnabled(true)             .series(arrayOf(                 AASeriesElement()                     .name("Tokyo")                     .data(arrayOf(                         arrayOf<Any?&gt;(6.9, 9.5, 14.5, 18.2, 21.5, null, null, null, null, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6)))                     .color(AAGradientColor.DeepSea)))     }
 
也就是说, 直接使用 null 对象占位即可.  AAChartCore-Kotlin 的 demo 中由此示例, 运行查看即可.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShuaiXiu** [comment]
大佬，改成这种数据格式就可以了
arrayOf(1,2,3,4,arrayOf<Any?&gt;(null),arrayOf<Any?&gt;(null),arrayOf<Any?&gt;(null))




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AAChartModel/AAChartCore-Kotlin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AAChartModel/AAChartCore-Kotlin] 大佬，如何修改饼图每个扇形的颜色！ (Issue #99)





 
kotlin 版本
     fun configureDiscontinuousDataChart(): AAChartModel {         return AAChartModel()             .chartType(AAChartType.Column)             .title("Discontinuous Data Chart")             .yAxisTitle("")             .dataLabelsEnabled(true)             .tooltipEnabled(true)             .series(arrayOf(                 AASeriesElement()                     .name("Tokyo")                     .data(arrayOf(                         arrayOf<Any?&gt;(6.9, 9.5, 14.5, 18.2, 21.5, null, null, null, null, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6)))                     .color(AAGradientColor.DeepSea)))     }
 
也就是说, 直接使用 null 对象占位即可.  AAChartCore-Kotlin 的 demo 中由此示例, 运行查看即可.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
